<?php View::content(); ?>
<?php echo Form::open() ?>




<div class="row">

    <div class="col-lg-2">

       <div class="form-group">
        <label>Años Lectivos</label>
        <select class="form-control" name ="idAnioF" id="idAnioF">
           <optgroup label="Años Lectivos Actuales">
              <?php foreach ($anio->items as $item) : ?>
                <option value='<?php echo $item->idAnio ?>'> <?php echo $item->idAnio?> </option>
            <?php endforeach; ?>
        </optgroup>
    </select>
</div>  

</div>

<div class="col-lg-3">

    <div class="form-group" style="display:none;">
        <input type="text" name="periodoN" id="periodoN" class="form-control" placeholder="Grado">
    </div>
    <label for="example">Seleccionar el periodo</label>

    <div class="form-group">
        <select class="form-control"  name ="periodoF"id="periodoF">
         <optgroup label="Periodos">
            <option value ="1">1</option>
            <option value ="2">2</option>
            <option value ="3">3</option>
            <option value ="4">4</option>
            
        </optgroup>
    </select>

</div>


</div>

<div class="col-lg-2">

    <div class="form-group" style="display:none;">
        <input type="text" name="gradoF" id="gradoF" class="form-control" placeholder="Grado">
    </div>
    <label for="exampleSelect1">Seleccionar el grado</label>

    <div class="form-group">
        <select class="form-control"  name ="gradoF"id="gradoF">
         <optgroup label="Grados">
            <option value ="13">Preescolar</option>
            <option value ="1">1</option>
            <option value ="2">2</option>
            <option value ="3">3</option>
            <option value ="4">4</option>
            <option value ="5">5</option>
            <option value ="6">6</option>
            <option value ="7">7</option>
            <option value ="8">8</option>
            <option value ="9">9</option>
            <option value ="10">10</option>
        </optgroup>
    </select>

</div>


</div>


<div class="col-lg-3">

    <div class="form-group" style="display:none;">
        <input type="text" name="grado" id="grado" class="form-control" placeholder="Grado">
    </div>
    <label for="exampleSelect1">Seleccionar la materia</label>

    <div class="form-group">
     <select class="form-control"  name ="idMateriaF" id="idMateriaF">
             <optgroup label="Materias Primaria">
                <option value ="MATEMATICAS">Matemáticas</option>
                <option value ="LENGUA CASTELLANA">Lengua Castellana</option>
                <option value ="INGLES">Inglés</option>
                <option value ="CIENCIAS SOCIALES">Ciencias Sociales</option>
                <option value ="CIENCIAS NATURALES">Ciencias Naturales</option>
                <option value ="EDUCACION ARTISTICA">Educación Artística</option>
                <option value ="EDUCACION RELIGIOSA">Educación Religiosa</option>
                <option value ="EDUCACION FISICA">Educación Física</option>
                <option value ="ETICA Y VALORES">Ética y Valores</option>
                <option value ="TECNOLOGIA E INFORMATICA">Tenología e Informática</option>
                
            </optgroup>
             <optgroup label="Materias Secundaria">
                <option value ="PROYECTO">Proyecto P.P.P</option>
                <option value ="MATEMATICAS">Matemáticas</option>
                <option value ="ESPAÑOL">Español</option>
                <option value ="QUIMICA">Química</option>
                <option value ="INGLES">Inglés</option>
                <option value ="EDUCACION FISICA">Educación Física</option>
                <option value ="FILOSOFIA">Filosofía</option>
                <option value ="ARTISTICA">Artística</option>
                <option value ="ETICA">Ética</option>
                <option value ="ECONOMIA">Economía</option>
                <option value ="FISICA">Física</option>
                <option value ="RELIGION">Religión</option>
                <option value ="INFORMATICA">Informática</option>   
            </optgroup>


          </select>

    </div>


</div>
</div>


<div class="row">

    <div class="col-lg-2">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar">Comenzar a modificar notas... 
            <!--?php echo Form::submit("Ingresar","class: boton"); ?--> 
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions" style="padding-left:40px;">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

<?php echo Form::close() ?>