<?php View::content(); ?>
<?php echo Form::open() ?>

 <div class="row">

    
       <div class="col-lg-6">

         <div class="panel panel-warning">
            <div class="panel-heading"> <center>AÑO LECTIVO ACTUAL</center></div>
            <div class="panel-body"> <center><h4 style ="color:#880e4f;"><b> <?php echo $_SESSION['globalYear']; ?></b></h4></center></div>
        </div>
        
      </div>


       <div class="col-lg-6">

          <div class="panel panel-warning">
            <div class="panel-heading"><center>SEDE ACTUAL</center></div>
            <div class="panel-body"> 
                <h4 style ="color:#880e4f;"> <center><b><?php 
        
        $t = $_SESSION['globalSede'];

        if($t=='belen'){

          echo "BELÉN";
        }elseif($t=='florida'){

        echo "LA FLORIDA";
        }
        elseif($t=='marqueza'){

          echo "LA MARQUEZA";
        }
        elseif($t=='lorenzo'){
          echo "SAN LORENZO";
          
        }else{

         echo "BELLAVISTA";
        }
        
         ?></b></h4></center>
            </div>
        </div>
       
      
      </div>



  </div>
  <hr>

<div class="row">

  


<div class="col-lg-3">

    <div class="form-group" style="display:none;">
        <input type="text" name="periodoN" id="periodoN" class="form-control" placeholder="Grado">
    </div>
    <label for="example">Seleccionar el periodo</label>

    <div class="form-group">
        <select class="form-control"  name ="periodoF"id="periodoF">
         <optgroup label="Periodos">
            <option value ="1">1</option>
            <option value ="2">2</option>
            <option value ="3">3</option>
            <option value ="4">4</option>
            
        </optgroup>
    </select>

</div>


</div>

<div class="col-lg-2">

    <div class="form-group" style="display:none;">
        <input type="text" name="gradoF" id="gradoF" class="form-control" placeholder="Grado">
    </div>
    <label for="exampleSelect1">Seleccionar el grado</label>

    <div class="form-group">
        <select class="form-control"  name ="gradoF"id="gradoF">
         <optgroup label="Grados">
            <option value ="13">Preescolar</option>
            <option value ="1">1</option>
            <option value ="2">2</option>
            <option value ="3">3</option>
            <option value ="4">4</option>
            <option value ="5">5</option>
            <option value ="6">6</option>
            <option value ="7">7</option>
            <option value ="8">8</option>
            <option value ="9">9</option>
            <option value ="10">10</option>
            <option value ="11">11</option>
        </optgroup>
    </select>

</div>


</div>


<div class="col-lg-3">

    <div class="form-group" style="display:none;">
        <input type="text" name="grado" id="grado" class="form-control" placeholder="Grado">
    </div>
    <label for="exampleSelect1">Seleccionar la materia</label>

    <div class="form-group">
     <select class="form-control"  name ="idMateriaF" id="idMateriaF">

     <optgroup label="Materias Preescolar">
                <option value ="CORPORAL">Corporal</option>
                <option value ="COMUNICATIVA">Comunicativa</option>
                <option value ="COGNITIVA">Cognitiva</option>
                <option value ="ETICA Y VALORES">Etica Y Valores</option>
                <option value ="ESTETICA">Estetica</option>
                <option value ="SOCIOAFECTIVA">Socioafectiva</option>
                <option value ="ESPIRITUAL">Espiritual</option>
                
             <optgroup label="Materias Primaria">
                <option value ="MATEMATICAS">Matemáticas</option>
                <option value ="LENGUA CASTELLANA">Lengua Castellana</option>
                <option value ="INGLES">Inglés</option>
                <option value ="CIENCIAS SOCIALES">Ciencias Sociales</option>
                <option value ="CIENCIAS NATURALES">Ciencias Naturales</option>
                <option value ="EDUCACION ARTISTICA">Educación Artística</option>
                <option value ="EDUCACION RELIGIOSA">Educación Religiosa</option>
                <option value ="EDUCACION FISICA">Educación Física</option>
                <option value ="ETICA Y VALORES">Ética y Valores</option>
                <option value ="TECNOLOGIA E INFORMATICA">Tenología e Informática</option>
                
            </optgroup>
             <optgroup label="Materias Secundaria">
                <option value ="PROYECTO">Proyecto P.P.P</option>
                <option value ="MATEMATICAS">Matemáticas</option>
                <option value ="ESPAÑOL">Español</option>
                <option value ="QUIMICA">Química</option>
                <option value ="INGLES">Inglés</option>
                <option value ="EDUCACION FISICA">Educación Física</option>
                <option value ="FILOSOFIA">Filosofía</option>
                <option value ="ARTISTICA">Artística</option>
                <option value ="ETICA">Ética</option>
                <option value ="ECONOMIA">Economía</option>
                <option value ="FISICA">Física</option>
                <option value ="RELIGION">Religión</option>
                <option value ="INFORMATICA">Informática</option>   
            </optgroup>


          </select>

    </div>


</div>
</div>


<div class="row">

    <div class="col-lg-2">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar">Comenzar a modificar notas... 
            <!--?php echo Form::submit("Ingresar","class: boton"); ?--> 
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions" style="padding-left:40px;">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

<?php echo Form::close() ?>