<?php View::content(); ?>


<div class="row">
<div class="col-md-5">

    <div class="col-lg-4">

        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open("generar/buscar/"); ?>
               <h4>Primer ó Segundo <b>nombre</b> del Estudiante</h4>
                <input type="text" name="nombresF" id ="nombresF" class="form-control" placeholder="Nombre o parte del nombre" required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>

    </div>
    </div>

     <div class="col-lg-2">

        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open("generar/buscar2/"); ?>
               <h4>Ingrese la <b>ID</b> del estudiante</h4>
                <input type="number" name="idF" id ="idF" class="form-control" placeholder="ID del estudiante" required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>

    </div>

</div>


<div class="row">

    <div class="col-lg-12">
        <div class="table-responsive">     
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                        <th>#</th>
                        <th>Documento</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                 
                        <th>Grado</th>
                        <th>Estado</th>
                        <th>Matricula</th>
                        <th>Acudiente</th>
                      
                        <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                         <?php for($i=0; $i<count($listaAlumnos); $i++) { ?>
                            <tr>
                                <td><?php echo $i ?></td>    
                                <td><?php echo $listaAlumnos[$i]->identidadAl ?></td>
                                <td><?php echo $listaAlumnos[$i]->nombre ?></td>
                                <td><?php echo $listaAlumnos[$i]->apellido ?></td>
                         
                                <td><?php echo $listaAlumnos[$i]->nombreGrado ?></td>
                                <td><?php echo $listaAlumnos[$i]->tipoEstado ?></td>
                                <td><?php echo $listaAlumnos[$i]->estadoMatricula ?></td>
                                <td><?php echo $listaAlumnos[$i]->nombreAcu ?></td>
                               
                                <td>
                                   <?php  $temp=$listaAlumnos[$i]->idAlumno; ?>

                                    <i class="fa fa-fw fa-edit"></i><?php echo Html::linkAction("cargarCarnet/$temp", ' Generar Carnet') ?>
                                 
                                </td>
                            </tr>
                             <?php } ?>
                        </tbody>
                    </table>
                     
            
        </div>
    </div>
</div>
<!-- /.row -->

<div class="row">

    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("create_carnet", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->
