<?php View::content(); ?>

<div class="row">
    <div class="col-lg-6">
        <div class="actions">
            <?= Html::linkAction("imprimir_final", 'Generar Planilla Final', 'class="btn btn-primary"') ?>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group input-group">
            <input type="text" class="form-control">
            <span class="input-group-btn"><button class="btn btn-default" type="button"><i class="fa fa-search"></i></button></span>
        </div>
    </div>
</div>

<br /><br />

<div class="row">

    <div class="col-lg-3">
        <div class="form-group">
            <input type="text" name="" id="" class="form-control" placeholder="Nombre Rector">
        </div>
        <div class="form-group">
            <label>Observaciones</label>
            <textarea class="form-control" rows="3"></textarea>
        </div>
    </div>

</div>

<br />