<?php
View::content();



 $css = file_get_contents('css/boot/bootstrap.css');

// Aquí será el creador de html


$listaAlumnos=$_SESSION['soloCarnet'];

$arrayH= array();

for ($i=0; $i<1; $i++) { 

   $arrayH[$i] = '
<html>

<head>



    <style>
        @page {
            sheet-size: Letter;
        }
        #example1 {
            background-image: url(img/carnet/plantillaC1.jpg);
            ;
            background-position: right bottom, left top;
            background-repeat: no-repeat, repeat;
            width: 816px;
            height: 220px;
        }
    </style>


</head>

<body>

    <div id="example1">
        <div style="margin-left:150px; padding-top:73px;">
            <h6></h6>
        </div>

        <div style="margin-left:106px; padding-top:15px;">
            <h6>'. $alumno->nombre .'</h6>
        </div>

        <div style="margin-left:106px; padding-top:-2px;">
            <h6>'.  $alumno->apellido.'</h6>
        </div>

        <div style="margin-left:106px; padding-top:-4px;">
            <h6>'.$alumno->identidadAl .'</h6>
        </div>


        <div style="margin-left:108px; padding-top:-8px; ">
            <h6>'. $alumno->rh .'</h6>

            <div style="margin-left:107px; padding-top:-8px; ">
                <h6>'. $grado->nombreGrado .'</h6>





                <div style="margin-left:250px; padding-top:-88px;">
                    <h6>'.$start.'</h6>
                </div>

                <div style="margin-left:460px; padding-top:-25px;">
                    <h6>'.$end.'</h6>
                </div>

                <div style="margin-left:324px; padding-top:2px;">
                    <h6><small>'. $alumno->dirAcu .'</small></h6>
                </div>


                <div style="margin-left:324 px; padding-top:-8px; ">
                    <h6><small>'. $alumno->celAcu .'</small></h6>

                    <div style="margin-left:384px; padding-top:1px; ">
                        <h6><small>'. $anio->anioRectora .'</small></h6>


                    </div>





                </div>

</body>

</html>
';



}



$html2='<br> <br>';
     Load::lib('mpdf');
    $mpdf = new mPDF('c','', 0, '', '0', '0', '0', '0', '0', '0', 'Letter');
    $arrayH[$i] = mb_convert_encoding($arrayH[$i], 'UTF-8', 'UTF-8');
        $html2 = mb_convert_encoding($html2, 'UTF-8', 'UTF-8');
    $mpdf->WriteHTML($css, 1);
   
   for ($i=0; $i <1 ; $i++) { 

    $mpdf->WriteHTML($arrayH[$i]);
    $mpdf->WriteHTML($html2);

 
   }
    
  
    
    $mpdf->Output('carnetSolo.pdf', 'I');

exit;
    ?>
