<?php

    View::content();
    Load::lib('pdf/mpdf');

    $css = file_get_contents('css/sbadmin/bootstrap.css');
    $html = '<div class="row text-center">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">INSTITUCIÓN EDUCATIVA BELÉN</th>
                        <th class="text-center">AÑO ESCOLAR 2016</th>
                        <th class="text-center">GRADO QUINTO A</th>
                        <th class="text-center">DOCENTE PEPITO PEREZ 34156872</th>
                        <th class="text-center">INFORME FINAL</th>
                    </tr>
                </thead>
             </table>
             <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th rowspan="2" class="middle text-center">No.</th>
                        <th rowspan="2" class="text-center">ESTUDIANTE</th>
                        <th rowspan="2" class="text-center">DOCUMENTO</th>
                        <th colspan="3" class="text-center">CÁLCULO</th>
                        <th colspan="3" class="text-center">MÉCANICA</th>
                        <th colspan="3" class="text-center">FISICA</th>
                        <th colspan="3" class="text-center">SOCIALES</th>
                        <th colspan="3" class="text-center">QUIMICA</th>
                    </tr>

                    <tr>
                        <th class="text-center">1</th>
                        <th class="text-center">EN</th>
                        <th class="text-center">FALTAS</th>

                        <th class="text-center">1</th>
                        <th class="text-center">EN</th>
                        <th class="text-center">FALTAS</th>

                        <th class="text-center">1</th>
                        <th class="text-center">EN</th>
                        <th class="text-center">FALTAS</th>

                        <th class="text-center">1</th>
                        <th class="text-center">EN</th>
                        <th class="text-center">FALTAS</th>

                        <th class="text-center">1</th>
                        <th class="text-center">EN</th>
                        <th class="text-center">FALTAS</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-center">1</td>
                        <td class="text-center">Carlos Castaño</td>
                        <td class="text-center">114384725</td>
                        
                        <td class="text-center">3,5</td>
                        <td class="text-center">B+</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">1,5</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">4,5</td>
                        <td class="text-center">S</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">2,5</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">8</td>
                        
                        <td class="text-center">3,8</td>
                        <td class="text-center">B+</td>
                        <td class="text-center">15</td>
                    </tr>

                    <tr>
                        <td class="text-center">2</td>
                        <td class="text-center">Che Guevara</td>
                        <td class="text-center">34785621</td>
                        
                        <td class="text-center">0,5</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">3</td>
                        
                        <td class="text-center">2,4</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">1</td>
                        
                        <td class="text-center">3,9</td>
                        <td class="text-center">B+</td>
                        <td class="text-center">0</td>
                        
                        <td class="text-center">3,5</td>
                        <td class="text-center">B+</td>
                        <td class="text-center">4</td>
                        
                        <td class="text-center">2,8</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">1</td>
                    </tr>

                    <tr>
                        <td class="text-center">3</td>
                        <td class="text-center">Eduardo Montealegre</td>
                        <td class="text-center">112354873</td>
                        
                        <td class="text-center">3,5</td>
                        <td class="text-center">B+</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">1,5</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">4,5</td>
                        <td class="text-center">S</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">2,5</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">8</td>
                        
                        <td class="text-center">3,8</td>
                        <td class="text-center">B+</td>
                        <td class="text-center">15</td>
                    </tr>

                    <tr>
                        <td class="text-center">4</td>
                        <td class="text-center">Simon Trinidad</td>
                        <td class="text-center">11235489</td>
                        
                        <td class="text-center">3,5</td>
                        <td class="text-center">B+</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">1,5</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">4,5</td>
                        <td class="text-center">S</td>
                        <td class="text-center">5</td>
                        
                        <td class="text-center">2,5</td>
                        <td class="text-center">B-</td>
                        <td class="text-center">8</td>
                        
                        <td class="text-center">3,8</td>
                        <td class="text-center">B+</td>
                        <td class="text-center">15</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<br />

<!-- /.row -->
<div class="row text-center">
    <div class="col-lg-3">
        <b>S=SUPERIOR</b>
    </div>
    <div class="col-lg-3">
        <b>A=ALTO</b>
    </div>
    <div class="col-lg-3">
        <b>B+=BASICO</b>
    </div>
    <div class="col-lg-3">
        <b>B-=BAJO</b>
    </div>
    <div class="col-lg-12">
        <b>OBSERVACIONES:</b>
    </div>
</div>


<br /><br /><br /><br />

<!-- /. Firmas -->
<div class="row text-center">
    <div class="col-lg-12">
        <hr>
        <b>Maria del Mar<br />Rector</b>
    </div>
</div>

<br />';

    $mpdf = new mPDF('c', 'A3');

    $mpdf->WriteHTML($css, 1);
    $mpdf->WriteHTML($html);
    $mpdf->Output('planilla_final.pdf', 'I');
?>