<?php

View::content();


$css = file_get_contents('css/sbadmin/bootstrap.css');

//for ($i=0; $i<count($listaAlumnos); $i++) { 

$html = '<div class="row text-center">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">PLANILLA POR PERIODOS</th>
                </tr>
            </thead>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">INSTITUCIÓN EDUCATIVA BELÉN</th>
                        <th class="text-center">AÑO ESCOLAR '.$periodo->anio_idAnio.'</th>
                        <th class="text-center">GRADO :'.$gradoF->nombreGrado.'</th>
                        
                        <th class="text-center">PERIODO:'. $periodo->numeroPeriodo .' </th>
                    </tr>
                </thead>
             </table>
             <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th  class="middle text-center">#</th>
                        <th  class="text-center"><small>NOMBRES</small></th>
                        <th  class="text-center"><small>APELLIDOS</small></th>
                        <th  class="text-center"><small>ID</small></th>
                        <th  colspan ="3" class="text-center"><small>MATEMÁTICAS</small></th>
                        <th colspan ="3" class="text-center"><small>LENGUA CASTELLANA</small></th>
                        <th  colspan ="3" class="text-center"><small>INGLÉS</small></th>
                        <th  colspan ="3" class="text-center"><small>CIENCIAS SOCIALES</small></th>
                        <th  colspan ="3" class="text-center"><small>CIENCIAS NATURALES</small></th>
                        <th  colspan ="3" class="text-center"><small>EDUCACIÓN ARTÍSTICA</small></th>
                        <th  colspan ="3" class="text-center"><small>EDUCACIÓN RELIGIOSA</small></th>
                        <th colspan ="3" class="text-center"><small>EDUCACIÓN FÍSICA</small></th>
                        <th colspan ="3" class="text-center"><small>ÉTICA Y VALORES</small></th>
                        <th colspan ="3" class="text-center"><small>TECNOLOGÍA E INFORMÁTICA</small></th>
                        <th colspan ="2" class="text-center"><small>VALORACIÓN</small></th>
                    </tr>

                    <tr>
                        <th  colspan="4" class="text-center"></th>
                       

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                         <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                         <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">PM</th>
                        <th class="text-center">PSTO</th>
                       
         
                    </tr>
                </thead>

                <tbody>  ';
// AQUÍ VA LA MATERIA MATEMATICAS
   $arrayP= array();
   $arrayZ= array();

for ($i=0; $i <$cuenta->cuenta ; $i++) { 
    $arrayZ[$i]=$i+1;
}


   $arrayF= array();

for ($i=0; $i <$cuenta->cuenta ; $i++) { 
    $html.=' <tr><td class="text-center">'.$i.'</td> ';

    $nF = round($listaNotasM[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escala="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escala="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escala="A"; 
    }else{

      $escala="S"; 
    }

     $nF = round($listaNotasL[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaL="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaL="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaL="A"; 
    }else{

      $escalaL="S"; 
    }

    ////////////////

      $nF = round($listaNotasI[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaI="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaI="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaI="A"; 
    }else{

      $escalaI="S"; 
    }

////////////// 
    $nF = round($listaNotasS[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaS="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaS="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaS="A"; 
    }else{

      $escalaS="S"; 
    }

    ////////////// 
    $nF = round($listaNotasN[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaN="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaN="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaN="A"; 
    }else{

      $escalaN="S"; 
    }

    ////////////// 
    $nF = round($listaNotasA[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaA="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaA="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaA="A"; 
    }else{

      $escalaA="S"; 
    }

    ////////////// 
    $nF = round($listaNotasR[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaR="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaR="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaR="A"; 
    }else{

      $escalaR="S"; 
    }

      ////////////// 
    $nF = round($listaNotasF[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaF="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaF="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaF="A"; 
    }else{

      $escalaF="S"; 
    }

    $nF = round($listaNotasE[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaE="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaE="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaE="A"; 
    }else{

      $escalaE="S"; 
    }

      ////////////// 
    $nF = round($listaNotasT[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escalaT="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaT="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaT="A"; 
    }else{

      $escalaT="S"; 
    }





$html.=' <td class="text-center">'.$listaNotasM[$i]->nombre.'</td> ';
$html.=' <td class="text-center">'.$listaNotasM[$i]->apellido.'</td> ';
$html.=' <td class="text-center">'.$listaNotasM[$i]->identidadAl.'</td> '; 

$html.=' <td class="text-center">'.round($listaNotasM[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escala .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasM[$i]->faltas.'</td> '; 

$html.=' <td class="text-center">'.round($listaNotasL[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaL .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasL[$i]->faltas.'</td> '; 

$html.=' <td class="text-center">'.round($listaNotasI[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaI .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasI[$i]->faltas.'</td> '; 

$html.=' <td class="text-center">'.round($listaNotasS[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaS .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasS[$i]->faltas.'</td> '; 

$html.=' <td class="text-center">'.round($listaNotasN[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaN .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasN[$i]->faltas.'</td> '; 

$html.=' <td class="text-center">'.round($listaNotasA[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaA .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasA[$i]->faltas.'</td> '; 

$html.=' <td class="text-center">'.round($listaNotasR[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaR .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasR[$i]->faltas.'</td> '; 

$html.=' <td class="text-center">'.round($listaNotasF[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaF .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasF[$i]->faltas.'</td>'; 

$html.=' <td class="text-center">'.round($listaNotasE[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaE .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasE[$i]->faltas.'</td>'; 
 
$html.=' <td class="text-center">'.round($listaNotasT[$i]->notaFinal,2).'</td> '; 
$html.=' <td class="text-center">'.$escalaT .'</td> '; 
$html.=' <td class="text-center">'.$listaNotasT[$i]->faltas.'</td>'; 

// Código para calcular promedio

$promedioP = $listaNotasM[$i]->notaFinal+$listaNotasL[$i]->notaFinal+
$listaNotasI[$i]->notaFinal+$listaNotasS[$i]->notaFinal+$listaNotasN[$i]->notaFinal+
$listaNotasA[$i]->notaFinal+$listaNotasR[$i]->notaFinal+$listaNotasF[$i]->notaFinal+
$listaNotasE[$i]->notaFinal+$listaNotasT[$i]->notaFinal;


$promedioF=$promedioP/10;


$html.=' <td class="text-center" >'.round($promedioF,2) .'</td> '; 

 $html.=' <td class="text-center">'.$arrayZ[$i].'</td></tr>';

} 

               


                $html.='
                    

                </tbody>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">S = SUPERIOR</th>
                        <th class="text-center">A = ALTO</th>
                        <th class="text-center">B+ = BÁSICO</th>
                        <th class="text-center">B- = BAJO</th>
                    </tr>
                </thead>
             </table>

                </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">N= NOTA FINAL</th>
                        <th class="text-center">E = ESCALA NACIONAL</th>
                        <th class="text-center">F = FALTAS</th>
                        <th class="text-center">PM = PROMEDIO </th>
                    </tr>


                </thead>
             </table>
        </div>
    </div>
</div>

<br />

<!-- /. Firmas -->
<div class="row text-center">
    <div class="col-lg-12">
        ________________________________
        <b> <br /> '. $anio2->anioRectora .'<br />Rector(a)</b>
    </div>
</div>

<br />';

//}
Load::lib('mpdf');

    $mpdf = new mPDF('c', 'Letter-L');
    $mpdf->debug = true;
    
$html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');

    $mpdf->WriteHTML($css, 1);
    $mpdf->WriteHTML($html);
    $mpdf->Output('planilla.pdf', 'I');
    exit;
?>