<?php
    View::content(); 
    Load::lib('pdf/mpdf');

    $css = file_get_contents('css/sbadmin/bootstrap.css');

    $html = '<div class="row text-center">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">INSTITUCIÓN EDUCATIVA BELÉN</th>
                        <th class="text-center">SISTEMA ACADEMICO</th>
                        <th class="text-center">AÑO ESCOLAR 2016</th>
                        <th class="text-center">CURSO '. $materia->grado . ' '. $materia->grupo .'</th>
                        <th class="text-center">'. $periodo .' PERIODO</th>
                    </tr>
                </thead>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">IDENTIFICACIÓN</th>
                        <th class="text-center">DOCENTE</th>
                        <th class="text-center">MATERIA</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td> '. $profesor->idProfesor .' </td>
                        <td> '. $nombresP[$materia->idMateria] .' </td>
                        <td> '. $materia->nombre .' </td>
                    </tr>
                </tbody>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">No.</th>
                        <th class="text-center">Identificación</th>
                        <th class="text-center">Nombres</th>
                        <th class="text-center">Apellidos</th>
                        <th class="text-center">Faltas</th>
                        <th class="text-center">Examen 1</th>
                        <th class="text-center">Examen 2</th>
                        <th class="text-center">Examen 3</th>
                        <th class="text-center">Examen 4</th>
                        <th class="text-center">Taller 1</th>
                        <th class="text-center">Taller 2</th>
                        <th class="text-center">PUESTO</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>34512826</td>
                        <td>Carlos Adrian</td>
                        <td>Ramirez Solis</td>
                        <td>3</td>
                        <td>2,3</td>
                        <td>3,2</td>
                        <td>1,5</td>
                        <td>4,2</td>
                        <td>1,2</td>
                        <td>2,5</td>
                        <td>9</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>2</td>
                        <td>34512826</td>
                        <td>Juan Sebastian</td>
                        <td>Collazos Ordoñez</td>
                        <td>10</td>
                        <td>1,5</td>
                        <td>3,2</td>
                        <td>4,2</td>
                        <td>2,3</td>
                        <td>1,2</td>
                        <td>2,5</td>
                        <td>5</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>3</td>
                        <td>34512826</td>
                        <td>Cristian Sterling</td>
                        <td>Quijano Laso</td>
                        <td>9</td>
                        <td>4,8</td>
                        <td>1,0</td>
                        <td>3,5</td>
                        <td>2,0</td>
                        <td>3,7</td>
                        <td>0,9</td>
                        <td>3</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>4</td>
                        <td>34512826</td>
                        <td>Javier Eduardo</td>
                        <td>Uzuriaga Laso</td>
                        <td>8</td>
                        <td>4,2</td>
                        <td>1,5</td>
                        <td>2,5</td>
                        <td>2,3</td>
                        <td>3,2</td>
                        <td>1,2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>5</td>
                        <td>34512826</td>
                        <td>Jesus Andres</td>
                        <td>Piedrahita Tintinago</td>
                        <td>2</td>
                        <td>2,0</td>
                        <td>3,7</td>
                        <td>1,0</td>
                        <td>0,9</td>
                        <td>4,8</td>
                        <td>3,5</td>
                        <td>15</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>6</td>
                        <td>34512826</td>
                        <td>Juan Sebastian</td>
                        <td>Collazos Ordoñez</td>
                        <td>10</td>
                        <td>1,5</td>
                        <td>3,2</td>
                        <td>4,2</td>
                        <td>2,3</td>
                        <td>1,2</td>
                        <td>2,5</td>
                        <td>5</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>7</td>
                        <td>34512826</td>
                        <td>Javier Eduardo</td>
                        <td>Uzuriaga Laso</td>
                        <td>8</td>
                        <td>4,2</td>
                        <td>1,5</td>
                        <td>2,5</td>
                        <td>2,3</td>
                        <td>3,2</td>
                        <td>1,2</td>
                        <td>1</td>
                    </tr>
                </tbody>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">S = Superior</th>
                        <th class="text-center">A = Alto</th>
                        <th class="text-center">B+ = Básico</th>
                        <th class="text-center">B- = Bajo</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row text-center">
    <div class="col-lg-12">
        <b>OBSERVACIONES: '. $observaciones .'</b>
    </div>
</div>
<!-- /.row -->


<br /><br />

<div class="row text-center">
    <div class="col-lg-2">
        ___________________________

        <b> <br />'. $nombreRector .'<br />Rector</b>
    </div>
</div>';


$mpdf = new mPDF('c', 'A4-L');
$mpdf->WriteHTML($css, 1);
$mpdf->WriteHTML($html);
$mpdf->Output('informe.pdf', 'I');

?>
