<?php View::content(); 



?>

<?php echo Form::open("generar/cargarCarnetsGrados/"); ?>

<div class="row">




  <div class="col-lg-12">

    <div class="panel panel-primary">
       <div class="panel-heading"># de estudiantes</div>
       <div class="panel-body">En este momento hay <b><?php $limite=$number->cuenta; echo $number->cuenta;?> </b>estudiantes en este curso</div>
    </div>

  </div>  

</div> <!-- Fin Header Row 1-->



<div class="row">

<div class="col-lg-3">


      
          <div class="form-group">
        <label>Nombre Rector(a)</label>
            
             <input type="text" name="rectorName" id="rectorName" class="form-control" value="<?php echo $anio->anioRectora; ?>" disabled>
            
        </div>
       <div class="form-group" style="display:none;">
            <input  name="rectorNameF" id="rectorNameF" class="form-control"  value="<?php echo $anio->anioRectora; ?>">
        </div>

        </div>
        <div class="col-lg-3">


        <div class="form-group">
        <label>Fecha Expedición</label>
            
      <input type="text" name="dateE" id="dateE" class="form-control" value="<?php echo date("d-m-Y");  ?>" disabled>
            
        </div>

         <div class="form-group" style="display:none;">
            <input  name="start" id="start" class="form-control"  value="<?php echo date("d-m-Y");  ?>" >
        </div>

        </div>

         <div class="form-group" style="display:none;">
            <input type="number" name="limite" id="limite" class="form-control"  value="<?php echo $limite; ?>">
        </div>

        <div class="col-lg-3">

    <div class="form-group">
        <label>Fecha de Caducidad</label>
        
            
  <input type="date" name="dateC" id="dateC" class="form-control" placeholder="dd-mm--aaaa" value="<?php echo date('d-m-Y',strtotime('+1 years'));  ?>" disabled>
            
        </div>

          <div class="form-group" style="display:none;">
            <input  name="end" id="end" class="form-control"  value="<?php echo date('d-m-Y',strtotime('+1 years'));  ?>" >
        </div>

       

       

</div>
<!-- Fin Columna 1 -->


        </div> <!-- Fin Row 1 -->


<div class="row">

    <div class="col-lg-2">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar" target="_blank" >Generar Boletines
            <!--?php echo Form::submit("Ingresar","class: boton"); ?--> 
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("create_carnet/", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<hr>
<!-- /.row -->
<div class="row">

    <div class="col-lg-12">
        <div class="table-responsive">     
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                        <th>#</th>
                        <th>Documento</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                 
                        <th class ="info">Grado</th>
                        <th>Estado</th>
                        <th>Matricula</th>
                       
                      
                            </tr>
                        </thead>
                        <tbody>
                         <?php for($i=0; $i<count($listaAlumnos); $i++) { ?>
                            <tr>
                                <td><?php echo $i ?></td>    
                                <td><?php echo $listaAlumnos[$i]->identidadAl ?></td>
                                <td><?php echo $listaAlumnos[$i]->nombre ?></td>
                                <td><?php echo $listaAlumnos[$i]->apellido ?></td>
                         
                                <td><?php echo $listaAlumnos[$i]->nombreGrado ?></td>
                                <td><?php echo $listaAlumnos[$i]->tipoEstado ?></td>
                                <td><?php echo $listaAlumnos[$i]->estadoMatricula ?></td>
                                
                               <?php 
                               

                                $_SESSION['grupoCarnet']=$listaAlumnos;

                               ?>
                              
                            </tr>
                             <?php } ?>
                        </tbody>
                    </table>
                     
            
        </div>
    </div>
</div>
<!-- /.row -->

<?php echo Form::close(); ?>
