<?php
    View::content();

    $temporal = intval($paciente->grado_idGrado);

    if($temporal == 13){
        $gradoActual = "PRESCOLAR";

    }elseif($temporal == 1){

        $gradoActual = "PRIMERO";
    }elseif($temporal == 2){
        $gradoActual = "SEGUNDO";

    }elseif($temporal == 3){

        $gradoActual = "TERCERO";
    }elseif($temporal == 4){
        $gradoActual = "CUARTO";

    }elseif($temporal == 5){

        $gradoActual = "QUINTO";
    }elseif($temporal == 6){
        $gradoActual = "SEXTO";

    }elseif($temporal == 7){

        $gradoActual = "SÉPTIMO";
    }elseif($temporal == 8){
        $gradoActual = "OCTAVO";

    }elseif($temporal == 9){
        $gradoActual = "NOVENO";

    }elseif($temporal == 10){

        $gradoActual = "DÉCIMO";
    }else{

      $gradoActual = "UNDÉCIMO"; 
    }
    

    
    $css = file_get_contents('css/sbadmin/bootstrap.css');

    $html = '<div class="row text-center">
    <div class="col-lg-4">
        <img src="../public/img/escudopdf.png" />
    </div>
    <div class="col-lg-4">
        REPUBLICA DE COLOMBIA <br />
        SECRETARÍA DE EDUCACIÓN DEPARTAMENTAL <br />
        COLEGIO DEPARTAMENTAL INSTITUCIÓN EDUCATIVA BELÉN <br />
        RESOLUCIÓN No. 9999 DE 2015 DECRETO 999 DE 2004 <br />
        NIT: 813.011.815-2 DANE 241359000160 <br />
        ISNOS - HUILA
    </div>
    <br>
    <div class="col-lg-4">
        <img src="../public/img/certificado/escudoBelen1Pequeno.png" />
    </div>
</div>

<br />

<div class="row text-center">
    <div class="col-lg-12">
        <p style ="text-align:justify;">
            El/la suscrito(a) Rector(a) de la Institución Educativa Belén 
            de Isnos - Huila, Modalidad Academica, calendario A y aprobada
             mediante Decreto N° 99 de 2005, emana de la Secretaría de Educación del Huila y Resolución
              de Aprobación de Estudios N° 0000 del 00 de Junio de 2000.
        </p>
        <br>
        <h4>CERTIFICA</h4>
        <br>
        <p style ="text-align:justify;" >Qué <b>'.$paciente->nombre.' '.$paciente->apellido.'</b> , identificado(a) con documento número '.$paciente->identidadAl.', se encuentra matriculado(a) y está cursando el grado
         <b>'.$gradoActual.'</b>, del plan de estudios nacional, esto con jornada académica diurna con horario de 8:00 am a 12:00 m y 2:00 pm a 4:00 pm.</p>


        <p style ="text-align:left;">Esta constancia se expide por razón de :<b> '. $razon .'</b></p>

    </div>
</div>

<div class="row text-center">
    <div class="col-lg-12">
        <div class="table-responsive">
        
           
        </div>
    </div>
</div>

<br />


<br /><br />

<!-- /. Firmas -->
<div class="row text-center">
    <div class="col-lg-6">
        <br/>
        <hr>
        <b>'. $nombreRector .'<br />Rector(a)</b>
    </div>
    <div class="col-lg-6 table-bordered">
        <p> Espacio para el sello de la entidad<br/><br/><br/><br/></p>
    </div>
</div>

<br />';

    Load::lib('mpdf');


    $mpdf = new mPDF('c', 'A4');

    $html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');

    $mpdf->WriteHTML($css, 1);
    $mpdf->WriteHTML($html);
    $mpdf->Output('certificado.pdf', 'I');
exit;


?>