<?php View::content(); ?>


<div class="row">

    <div class="col-lg-3">
        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open(); ?>
               <h4>Nombre</h4>
                <input type="hidden" name="valN" id ="valN" value="2">
                <input type="text" name="nombreP" id ="nombreP" class="form-control" placeholder="Introducir Nombre" required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>
    </div>



     <div class="col-lg-3" style ="margin-left:30px;">
        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open(); ?>
               <h4>Apellido</h4>
                <input type="hidden" name="valA" id ="valA" value="2">
                <input type="text" name="apellidoP" id ="apellidoP" class="form-control" placeholder="Introducir Apellido" required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>
    </div>



     <div class="col-lg-3" style ="margin-left:30px;">
        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open(); ?>
               <h4>Identificación </h4>
                <input type="hidden" name="valI" id ="valI" value="2">
                <input type="text" name="cedulaP" id ="cedulaP" class="form-control" placeholder="Tarjeta ó cédula" required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>
    </div>


</div>

<!-- /.row -->


        <!-- /.row -->

        <br>

        <h4>Lista de estudiantes</h4>
        <div class="row">

            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-inverse">
                            <tr>
                                <th>Identificación</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                            
                                <th>Género</th>
                                <th>Edad</th>
                                <th>RH</th>
                                <th>Dirección</th>
                                <th>Acudiente </th>
                               
                                
                                <th>Cel Acudiente</th>
                                <th>Grado</th>
                                <th>Certificado </th>
                                
                                   
                                </tr>
                            </thead>
                            <tbody>
                                <?php for($i=0; $i<count($listaPacientes); $i++) { ?>
                                    <tr>
                                        <td><?php echo $listaPacientes[$i]->identidadAl ?></td>
                                        <td><?php echo $listaPacientes[$i]->nombre ?></td>
                                        <td><?php echo $listaPacientes[$i]->apellido ?></td>
                                   
                                       

                                        <td><b><?php echo $listaPacientes[$i]->genero ?></b></td>
                                        

                                        <td><?php echo $listaPacientes[$i]->edad ?></td><!-- revisar codigo para edad -->

                                        <td><?php echo $listaPacientes[$i]->rh ?></td>
                                        

                                        <td><?php echo $listaPacientes[$i]->dir ?></td>

                                        

                                        <td><?php echo $listaPacientes[$i]->nombreAcu ?></td>

                                        <td><?php echo $listaPacientes[$i]->celAcu ?></td>
                                        <td><?php echo $listaPacientes[$i]->grado_idGrado ?></td>
                                  
                                        <?php 

                                         $idPaciente = $listaPacientes[$i]->idAlumno;
                                         //verificar si se envia

                                        ?>
                                          <td>
                                        <i class="fa fa-hospital-o"></i><?php echo Html::linkAction("nuevoCertificado/$idPaciente", ' Generar certificado') ?>
                                        </td>

                                         

                                      
                                    </tr>
                                  <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <!-- /.row -->
<!-- /.row -->

<div class="row">

    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->
