<footer>
    <div class="col-12 text-center">
        <ul class="inline" >
        	<li><a href='#'>Isnos - Huila</a> |</li>
        	<li><a href='#'>Vereda Belén</a> |</li>
        	<li><a href='#'>Teléfono: 3134539588</a> |</li>
        	<li><a href='' title=''>DANE: 241359000160</a></li>
        </ul>
    </div>
    <!--div class="col-12 text-center">
        <p> <a title="">Isnos - Huila</a> | 
        	<a target="_blank" title="">Vereda Belén</a> | 
        	<a title="">Teléfono: 3134539588</a> |
            <a title="">DANE: 241359000160</a></p>
    </div-->
    <div class="col-12 text-center">
        <a href='#'>© <?= date('Y')?></a>
        
    </div>
    <!--div class="col-12 text-center"> <?= 'Ejecutado en ', round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT'])*1000, 4), ' ms. usando ', number_format(memory_get_usage() / 1048576, 3), ' MB de memoria'?></div!-->
</footer>
