<?php View::content(); ?>

<?php echo Form::open(); ?>


  <div class="row">
       <div class="col-lg-6">
         <div class="panel panel-warning">
            <div class="panel-heading"> <center>AÑO LECTIVO ACTUAL</center></div>
            <div class="panel-body"> <center><h4 style ="color:#880e4f;"><b> <?php echo $_SESSION['globalYear']; ?></b></h4></center></div>
        </div>  
      </div>
  <div class="col-lg-6">
          <div class="panel panel-warning">
            <div class="panel-heading"><center>SEDE ACTUAL</center></div>
            <div class="panel-body"> 
                <h4 style ="color:#880e4f;"> <center><b><?php 
        $t = $_SESSION['globalSede'];
        if($t=='belen'){
          echo "BELÉN";
        }elseif($t=='florida'){
        echo "LA FLORIDA";
        }
        elseif($t=='marqueza'){
          echo "LA MARQUEZA";
        }
        elseif($t=='lorenzo'){
          echo "SAN LORENZO";
                 }else{
         echo "BELLAVISTA";
        }
                 ?></b></h4></center>
            </div>
        </div>
 
      </div><!-- end panel row -->



<div class="row">

<h3 style="margin-left:15px; color:#3f51b5" >Informes por periodos</h3>
  <input value ="2" name="formulario1" type ="hidden"> 


<div class="col-lg-2">



   <h4>Grado</h4>

   <div class="form-group">
    <select class="form-control"  name ="gradoA" id="gradoA">
       <optgroup label="Grados Actuales">
        <option value ="13" selected >Preescolar</option>
        <option value ="1">Primero</option>
        <option value ="2">Segundo</option>
        <option value ="3">Tercero</option>
        <option value ="4">Cuarto</option>
        <option value ="5">Quinto</option>
        <option value ="6">Sexto</option>
        <option value ="7">Séptimo</option>
        <option value ="8">Octavo</option>
        <option value ="9">Noveno</option>
        <option value ="10">Décimo</option> 
        <option value ="11">Undécimo</option> 
    </optgroup>
</select>
</div>


</div>



<div class="col-lg-3">

   

    <h4>Materia</h4>

    <div class="form-group">
        <select class="form-control"  name ="materiaA" id="materiaA">

        <optgroup label="Materias Preescolar">
                <option value ="CORPORAL">Corporal</option>
                <option value ="COMUNICATIVA">Comunicativa</option>
                <option value ="COGNITIVA">Cognitiva</option>
                <option value ="ETICA Y VALORES">Etica Y Valores</option>
                <option value ="ESTETICA">Estetica</option>
                <option value ="SOCIOAFECTIVA">Socioafectiva</option>
                <option value ="ESPIRITUAL">Espiritual</option>

           <optgroup label="Materias Primaria">
            <option value ="MATEMATICAS" selected >Matemáticas</option>
            <option value ="LENGUA CASTELLANA">Lengua Castellana</option>
            <option value ="INGLES">Inglés</option>
            <option value ="CIENCIAS SOCIALES">Ciencias Sociales</option>
            <option value ="CIENCIAS NATURALES">Ciencias Naturales</option>
            <option value ="EDUCACION ARTISTICA">Educación Artística</option>
            <option value ="EDUCACION RELIGIOSA">Educación Religiosa</option>
            <option value ="EDUCACION FISICA">Educación Física</option>
            <option value ="ETICA Y VALORES">Ética y Valores</option>
            <option value ="TECNOLOGIA E INFORMATICA">Tenología e Informática</option>

        </optgroup>
        <optgroup label="Materias Secundaria">
            <option value ="PROYECTO">Proyecto P.P.P</option>
            <option value ="MATEMATICAS">Matemáticas</option>
            <option value ="ESPAÑOL">Español</option>
            <option value ="QUIMICA">Química</option>
            <option value ="INGLES">Inglés</option>
            <option value ="EDUCACION FISICA">Educación Física</option>
            <option value ="FILOSOFIA">Filosofía</option>
            <option value ="ARTISTICA">Artística</option>
            <option value ="ETICA">Ética</option>
            <option value ="ECONOMIA">Economía</option>
            <option value ="FISICA">Física</option>
            <option value ="RELIGION">Religión</option>  
            <option value ="INFORMATICA">Religión</option>  
        </optgroup>


    </select>
</div>


</div>


<div class="col-lg-2">



   <h4>Periodo</h4>

   <div class="form-group">
    <select class="form-control"  name ="periodoA" id="periodoA">
       <optgroup label="Periodos Actuales">

        <option value ="1" selected>Primero</option>
        <option value ="2">Segundo</option>
        <option value ="3">Tercero</option>
        <option value ="4">Cuarto</option>

    </optgroup>
</select>
</div>


</div>

<div class="col-lg-2" style="padding-top:40px;">
    <button class="btn btn-primary waves-effect waves-light" type="submit" name="Ingresar">Generar Informe
        <!--?php echo Form::submit("Ingresar","class: boton"); ?--> 
    </button>
</div>




</div>

<?php echo Form::close(); ?>
<!-- Aquí termina la prima fila planillas con NOTASSS-->

<!-- Aquí termina la prima fila planillas con VACIOOOO-->
<?php echo Form::open("informe/vacia"); ?>
<hr>


<div class="row">
<div class="col-lg-2">

   <h4>Grado</h4>

   <div class="form-group">
    <select class="form-control"  name ="gradoB" id="gradoB">
       <optgroup label="Grados Actuales">
        <option value ="13" selected >Preescolar</option>
        <option value ="1">Primero</option>
        <option value ="2">Segundo</option>
        <option value ="3">Tercero</option>
        <option value ="4">Cuarto</option>
        <option value ="5">Quinto</option>
        <option value ="6">Sexto</option>
        <option value ="7">Séptimo</option>
        <option value ="8">Octavo</option>
        <option value ="9">Noveno</option>
        <option value ="10">Décimo</option> 
        <option value ="11">Undécimo</option> 
    </optgroup>
</select>
</div>


</div>



<div class="col-lg-3">

    <div class="form-group" style="display:none;">
    <input type="text" name="periodoR" id="periodoR"  class="form-control" value="2">
    </div>

    <h4>Materia</h4>

    <div class="form-group">
        <select class="form-control"  name ="materiaB" id="materiaB">

        <optgroup label="Materias Preescolar">
                <option value ="CORPORAL">Corporal</option>
                <option value ="COMUNICATIVA">Comunicativa</option>
                <option value ="COGNITIVA">Cognitiva</option>
                <option value ="ETICA Y VALORES">Etica Y Valores</option>
                <option value ="ESTETICA">Estetica</option>
                <option value ="SOCIOAFECTIVA">Socioafectiva</option>
                <option value ="ESPIRITUAL">Espiritual</option>
                
           <optgroup label="Materias Primaria">
            <option value ="MATEMATICAS" selected >Matemáticas</option>
            <option value ="LENGUA CASTELLANA">Lengua Castellana</option>
            <option value ="INGLES">Inglés</option>
            <option value ="CIENCIAS SOCIALES">Ciencias Sociales</option>
            <option value ="CIENCIAS NATURALES">Ciencias Naturales</option>
            <option value ="EDUCACION ARTISTICA">Educación Artística</option>
            <option value ="EDUCACION RELIGIOSA">Educación Religiosa</option>
            <option value ="EDUCACION FISICA">Educación Física</option>
            <option value ="ETICA Y VALORES">Ética y Valores</option>
            <option value ="TECNOLOGIA E INFORMATICA">Tenología e Informática</option>

        </optgroup>
        <optgroup label="Materias Secundaria">
            <option value ="PROYECTO">Proyecto P.P.P</option>
            <option value ="MATEMATICAS">Matemáticas</option>
            <option value ="ESPAÑOL">Español</option>
            <option value ="QUIMICA">Química</option>
            <option value ="INGLES">Inglés</option>
            <option value ="EDUCACION FISICA">Educación Física</option>
            <option value ="FILOSOFIA">Filosofía</option>
            <option value ="ARTISTICA">Artística</option>
            <option value ="ETICA">Ética</option>
            <option value ="ECONOMIA">Economía</option>
            <option value ="FISICA">Física</option>
            <option value ="RELIGION">Religión</option>  
            <option value ="INFORMATICA">Religión</option>  
        </optgroup>


    </select>
</div>


</div>

<div class="col-lg-2">



   <h4>Periodo</h4>

   <div class="form-group">
    <select class="form-control"  name ="periodoB" id="periodoB">
       <optgroup label="Periodos Actuales">

        <option value ="1" selected >Primero</option>
        <option value ="2">Segundo</option>
        <option value ="3">Tercero</option>
        <option value ="4">Cuarto</option>

            </optgroup>
        </select>
        </div>


</div>


<div class="col-lg-2" style="padding-top:40px;">
    <button class="btn btn-warning waves-effect waves-light" type="submit" name="Ingresar">Generar informe vacío 
        <!--?php echo Form::submit("Ingresar","class: boton"); ?--> 
    </button>
</div>


</div>
<hr>


<?php echo Form::close(); ?>

<?php echo Form::open('informe/ultimo'); ?>
<div class ="row">
    <h3 style="margin-left:15px; color:#3f51b5">Informe final</h3>
    <div class ="col-lg-7">

         <h4>Grado</h4>

   <div class="form-group">
    <select class="form-control"  name ="gradoFinal" id="gradoFinal">
       <optgroup label="Grados Actuales">
        <option value ="13" selected >Preescolar</option>
        <option value ="1">Primero</option>
        <option value ="2">Segundo</option>
        <option value ="3">Tercero</option>
        <option value ="4">Cuarto</option>
        <option value ="5">Quinto</option>
        <option value ="6">Sexto</option>
        <option value ="7">Séptimo</option>
        <option value ="8">Octavo</option>
        <option value ="9">Noveno</option>
        <option value ="10">Décimo</option> 
        <option value ="11">Undécimo</option> 
    </optgroup>
</select>
</div><!-- end grade chooser -->




    </div>

    
<div class="col-lg-2" style="padding-top:40px;">
    <button class="btn btn-danger waves-effect waves-light" type="submit" name="Ingresar">Generar informe final 
        <!--?php echo Form::submit("Ingresar","class: boton"); ?--> 
    </button>
</div>

</div>

<?php echo Form::close(); ?>