<?php

View::content();


$css = file_get_contents('css/sbadmin/bootstrap.css');

//for ($i=0; $i<count($listaAlumnos); $i++) { 

$html = '<div class="row text-center">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">INFORME FINAL</th>
                </tr>
            </thead>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">INSTITUCIÓN EDUCATIVA BELÉN</th>
                        <th class="text-center">AÑO ESCOLAR '.$anioG.'</th>
                        <th class="text-center">GRADO :'.$gradoSel.'</th>
                        
                        <th class="text-center">PERIODO:1-4 </th>
                    </tr>
                </thead>
             </table>
             <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th  class="middle text-center">#</th>
                        <th  class="text-center"><small>NOMBRES</small></th>
                        <th  class="text-center"><small>APELLIDOS</small></th>
                        <th  class="text-center"><small>ID</small></th>
                        <th  colspan ="3" class="text-center"><small>CORPORAL</small></th>
                        <th colspan ="3" class="text-center"><small>COMUNICATIVA</small></th>
                        <th  colspan ="3" class="text-center"><small>COGNITIVA</small></th>
                        <th  colspan ="3" class="text-center"><small>ETICA Y VALORES</small></th>
                        <th  colspan ="3" class="text-center"><small>ESTETICA</small></th>
                        <th  colspan ="3" class="text-center"><small>SOCIOAFECTIVA FISICA</small></th>
                        <th  colspan ="3" class="text-center"><small>ESPIRITUAL</small></th>
                        
                    </tr>

                    <tr>
                        <th  colspan="4" class="text-center"></th>
                       

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                         <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>


                        <th class="text-center">PM</th>
                        <th class="text-center">PSTO</th>
                        <th class="text-center">FT</th>
                       
         
                    </tr>
                </thead>

                <tbody>  ';
// AQUÍ VA LA MATERIA MATEMATICAS
   $arrayP= array();
   $arrayZ= array();

for ($i=0; $i <$cuenta->cuenta ; $i++) { 
    $arrayZ[$i]=$i+1;
}



for ($i=0; $i <$cuenta->cuenta ; $i++) { 
    $html.=' <tr><td class="text-center">'.($i+1).'</td> ';

   

    /* VARIABLES TEMPORALES PARA GUARDAR LOS PROMEDIOS */

    $notaCorporal = round(($listaNotasCor1[$i]->notaFinal + $listaNotasCor2[$i]->notaFinal + 
    $listaNotasCor3[$i]->notaFinal + $listaNotasCor4[$i]->notaFinal )/4,2);

    $notaComunicativa = round(($listaNotasCom1[$i]->notaFinal + $listaNotasCom2[$i]->notaFinal + 
    $listaNotasCom3[$i]->notaFinal + $listaNotasCom4[$i]->notaFinal )/4,2);

    $notaCognitiva = round(($listaNotasCog1[$i]->notaFinal + $listaNotasCog2[$i]->notaFinal + 
    $listaNotasCog3[$i]->notaFinal + $listaNotasCog4[$i]->notaFinal )/4,2);

    $notaEtica = round(($listaNotasEti1[$i]->notaFinal + $listaNotasEti2[$i]->notaFinal + 
    $listaNotasEti3[$i]->notaFinal + $listaNotasEti4[$i]->notaFinal )/4,2);

    $notaEstetica = round(($listaNotasEst1[$i]->notaFinal + $listaNotasEst2[$i]->notaFinal + 
    $listaNotasEst3[$i]->notaFinal + $listaNotasEst4[$i]->notaFinal )/4,2);

    $notaSocioafectiva = round(($listaNotasSoc1[$i]->notaFinal + $listaNotasSoc2[$i]->notaFinal + 
    $listaNotasSoc3[$i]->notaFinal + $listaNotasSoc4[$i]->notaFinal )/4,2);

    $notaEspiritual= round(($listaNotasEsp1[$i]->notaFinal + $listaNotasEsp2[$i]->notaFinal + 
    $listaNotasEsp3[$i]->notaFinal + $listaNotasEsp4[$i]->notaFinal )/4,2);

    

    /* SUMARIAZACION DE FALTAS*/

     $faltaCorporal = $listaNotasCor1[$i]->faltas + $listaNotasCor2[$i]->faltas + 
    $listaNotasCor3[$i]->faltas + $listaNotasCor4[$i]->faltas ;

    $faltaComunicativa = $listaNotasCom1[$i]->faltas + $listaNotasCom2[$i]->faltas + 
    $listaNotasCom3[$i]->faltas + $listaNotasCom4[$i]->faltas ;

    $faltaCognitiva = $listaNotasCog1[$i]->faltas + $listaNotasCog2[$i]->faltas + 
    $listaNotasCog3[$i]->faltas + $listaNotasCog4[$i]->faltas ;

    $faltaEtica = $listaNotasEti1[$i]->faltas + $listaNotasEti2[$i]->faltas + 
    $listaNotasEti3[$i]->faltas + $listaNotasEti4[$i]->faltas ;

    $faltaEstetica = $listaNotasEst1[$i]->faltas + $listaNotasEst2[$i]->faltas + 
    $listaNotasEst3[$i]->faltas + $listaNotasEst4[$i]->faltas ;

    $faltaSocioafectiva = $listaNotasSoc1[$i]->faltas + $listaNotasSoc2[$i]->faltas + 
    $listaNotasSoc3[$i]->faltas + $listaNotasSoc4[$i]->faltas ;

    $faltaEspiritual= $listaNotasEsp1[$i]->faltas + $listaNotasEsp2[$i]->faltas + 
    $listaNotasEsp3[$i]->faltas + $listaNotasEsp4[$i]->faltas ;

    



     $nF=$notaCorporal;
    if($nF>=0 and $nF <=2.9){

        $escalaP="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaP="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaP="A"; 
    }else{

      $escalaP="S"; 
    }

     $nF = $notaComunicativa;
    if($nF>=0 and $nF <=2.9){

        $escalaM="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaM="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaM="A"; 
    }else{

      $escalaM="S"; 
    }

    ////////////////

      $nF = $notaCognitiva;
    if($nF>=0 and $nF <=2.9){

        $escalaES="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaES="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaES="A"; 
    }else{

      $escalaES="S"; 
    }

////////////// 
    $nF = $notaEtica;
    if($nF>=0 and $nF <=2.9){

        $escalaQ="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaQ="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaQ="A"; 
    }else{

      $escalaQ="S"; 
    }

    ////////////// 
    $nF = $notaEstetica;
    if($nF>=0 and $nF <=2.9){

        $escalaI="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaI="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaI="A"; 
    }else{

      $escalaI="S"; 
    }

    ////////////// 
    $nF = $notaSocioafectiva;
    if($nF>=0 and $nF <=2.9){

        $escalaEF="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaEF="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaEF="A"; 
    }else{

      $escalaEF="S"; 
    }

    ////////////// 
    $nF = $notaEspiritual;
    if($nF>=0 and $nF <=2.9){

        $escalaFI="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaFI="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaFI="A"; 
    }else{

      $escalaFI="S"; 
    }

    





$html.=' <td class="text-center">'.$listaNotasCor1[$i]->nombre.'</td> ';
$html.=' <td class="text-center">'.$listaNotasCor1[$i]->apellido.'</td> ';
$html.=' <td class="text-center">'.$listaNotasCor1[$i]->identidadAl.'</td> '; 

$html.=' <td class="text-center">'.$notaCorporal.'</td> '; 
$html.=' <td class="text-center">'.$escalaP .'</td> '; 
$html.=' <td class="text-center">'.$faltaCorporal.'</td> '; 

$html.=' <td class="text-center">'.$notaComunicativa.'</td> '; 
$html.=' <td class="text-center">'.$escalaM .'</td> '; 
$html.=' <td class="text-center">'.$faltaComunicativa.'</td> '; 

$html.=' <td class="text-center">'.$notaCognitiva.'</td> '; 
$html.=' <td class="text-center">'.$escalaES .'</td> '; 
$html.=' <td class="text-center">'.$faltaCognitiva.'</td> '; 

$html.=' <td class="text-center">'.$notaEtica.'</td> '; 
$html.=' <td class="text-center">'.$escalaQ .'</td> '; 
$html.=' <td class="text-center">'.$faltaEtica.'</td> '; 

$html.=' <td class="text-center">'.$notaEstetica.'</td> '; 
$html.=' <td class="text-center">'.$escalaI .'</td> '; 
$html.=' <td class="text-center">'.$faltaEstetica.'</td> '; 

$html.=' <td class="text-center">'.$notaSocioafectiva.'</td> '; 
$html.=' <td class="text-center">'.$escalaEF .'</td> '; 
$html.=' <td class="text-center">'.$faltaSocioafectiva.'</td> '; 

$html.=' <td class="text-center">'.$notaEspiritual.'</td> '; 
$html.=' <td class="text-center">'.$escalaFI .'</td> '; 
$html.=' <td class="text-center">'.$faltaEspiritual.'</td> '; 


// Código para calcular promedio

$promedioP = $notaCorporal + $notaComunicativa + $notaCognitiva + $notaEtica + $notaEstetica + $notaSocioafectiva 
+ $notaEspiritual;


$promedioF=$promedioP/7;

$faltasTotales = $faltaCorporal + $faltaComunicativa + $faltaCognitiva + $faltaEtica + $faltaEstetica + $faltaSocioafectiva 
+ $faltaEspiritual;

$html.=' <td class="text-center" >'.round($promedioF,2) .'</td> '; 

 
 $html.=' <td class="text-center">'.$arrayZ[$i].'</td>';

 $html.=' <td class="text-center">'.$faltasTotales.'</td></tr>';

} 

               


                $html.='
                    

                </tbody>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">S = SUPERIOR</th>
                        <th class="text-center">A = ALTO</th>
                        <th class="text-center">B+ = BÁSICO</th>
                        <th class="text-center">B- = BAJO</th>
                    </tr>
                </thead>
             </table>

                </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">N= NOTA FINAL</th>
                        <th class="text-center">E = ESCALA NACIONAL</th>
                        <th class="text-center">F = FALTAS</th>
                        <th class="text-center">PM = PROMEDIO </th>
                    </tr>


                </thead>
             </table>
        </div>
    </div>
</div>

<br />

<!-- /. Firmas -->
<div class="row text-center">
    <div class="col-lg-12">
        ________________________________
        <b> <br /> Test rector<br />Rector(a)</b>
    </div>
</div>

<br />';

//}
Load::lib('mpdf');

    $mpdf = new mPDF('utf-8', array(330,216));
    $mpdf->debug = true;
    
$html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');

    $mpdf->WriteHTML($css, 1);
    $mpdf->WriteHTML($html);
    $mpdf->Output('informeFinal.pdf', 'I');
    exit;
?>