<?php
    View::content(); 
    Load::lib('mpdf');

    $css = file_get_contents('css/sbadmin/bootstrap.css');

    $html = '<div class="row text-center">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">INSTITUCIÓN EDUCATIVA BELÉN</th>
                        <th class="text-center">SISTEMA ACADEMICO</th>
                        <th class="text-center">AÑO ESCOLAR 2017</th>
                        <th class="text-center">CURSO:'. $grado->nombreGrado .'</th>
                        <th class="text-center">PERIODO:'. $periodo.' </th>
                    </tr>
                </thead>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">IDENTIFICACIÓN</th>
                        <th class="text-center">DOCENTE</th>
                        <th class="text-center">MATERIA</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th class="text-center" > '. $profesor->identidadPro .' </th>
                        <th class="text-center"> '.$profesor->nombrePro.' '.$profesor->apellidoPro.' </th>
                        <th class="text-center"> '. $materia->nombreMateria .' </th>
                    </tr>
                </tbody>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">No.</th>
                        <th class="text-center">Nombres</th>
                        <th class="text-center">Apellidos</th>
                        <th class="text-center">ID</th>
                        <th class="text-center">FALT</th>
                        <th class="text-center">TALLER</th>
                        <th class="text-center">PRUEBA ESCRITA</th>
                        <th class="text-center">LABORATORIOS</th>
                        <th class="text-center">EVALUACION ORAL</th>
                        <th class="text-center">EVALUACION ESCRITA</th>
                        <th class="text-center">PUNTUALIDAD</th>
                        <th class="text-center">PRESENTACION PERSONAL</th>
                        <th class="text-center">COMPORTAMIENTO</th>
                        <th class="text-center">INTERES Y PARTICIPACION</th>
                        <th class="text-center">VALORACION</th>
                        <th class="text-center">NOTA</th>
                        <th class="text-center">PUESTO</th>
                    </tr>
                </thead>
                <tbody>  ';
// AQUÍ VA LA MATERIA MATEMATICAS
 
// TR Fila TD Casilla dentro de la fila
   
for ($i=0; $i <$cuenta->cuenta ; $i++) { 
    

   $nF = round($listaAlumnos[$i]->notaFinal,2);
    if($nF>=0 and $nF <=2.9){

        $escala="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escala="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escala="A"; 
    }else{

      $escala="S"; 
    }



$html.=' <tr><td class="text-center">'.($i+1).'</td> ';
$html.=' <td class="text-center">'.$listaAlumnos[$i]->nombre.'</td> ';
$html.=' <td class="text-center">'.$listaAlumnos[$i]->apellido.'</td> ';
$html.=' <td class="text-center">'.$listaAlumnos[$i]->identidadAl.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->faltas.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->taller.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->pEscrita.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->labs.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->eOral.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->eEscrita.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->punt.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->pPersonal.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->comp.'</td> '; 
$html.=' <td class="text-center">'.$listaAlumnos[$i]->iParticipacion.'</td> '; 
$html.=' <td class="text-center">'.round($listaAlumnos[$i]->notaFinal,2).'</td> ';
$html.=' <td class="text-center">'.$escala .'</td> ';
$html.=' <td class="text-center">'.($i+1) .'</td></tr> ';





} 

               


                $html.='
                    

                </tbody>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">S = Superior</th>
                        <th class="text-center">A = Alto</th>
                        <th class="text-center">B+ = Básico</th>
                        <th class="text-center">B- = Bajo</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row text-center">
    <div class="col-lg-12">
        <b>OBSERVACIONES: </b>
    </div>
</div>
<!-- /.row -->


<br /><br />

<div class="row text-center">
    <div class="col-lg-2">
        ___________________________

          <b> <br />'. $anio->anioRectora .'<br />Rector(a)</b>
    </div>
</div>';


$mpdf = new mPDF('c', 'Letter-L');
$mpdf->debug = true;

$html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');
$mpdf->WriteHTML($css, 1);
$mpdf->WriteHTML($html);
$mpdf->Output('informe.pdf', 'I');
exit;

?>
