<?php

View::content();


$css = file_get_contents('css/sbadmin/bootstrap.css');

//for ($i=0; $i<count($listaAlumnos); $i++) { 

$html = '<div class="row text-center">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">INFORME FINAL</th>
                </tr>
            </thead>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">INSTITUCIÓN EDUCATIVA BELÉN</th>
                        <th class="text-center">AÑO ESCOLAR '.$anioG.'</th>
                        <th class="text-center">GRADO :'.$gradoSel.'</th>
                        
                        <th class="text-center">PERIODO:1-4 </th>
                    </tr>
                </thead>
             </table>
             <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th  class="middle text-center">#</th>
                        <th  class="text-center"><small>NOMBRES</small></th>
                        <th  class="text-center"><small>APELLIDOS</small></th>
                        <th  class="text-center"><small>ID</small></th>
                        <th  colspan ="3" class="text-center"><small>MATEMÁTICAS</small></th>
                        <th colspan ="3" class="text-center"><small>LENGUA CASTELLANA</small></th>
                        <th  colspan ="3" class="text-center"><small>INGLÉS</small></th>
                        <th  colspan ="3" class="text-center"><small>CIENCIAS SOCIALES</small></th>
                        <th  colspan ="3" class="text-center"><small>CIENCIAS NATURALES</small></th>
                        <th  colspan ="3" class="text-center"><small>EDUCACIÓN ARTÍSTICA</small></th>
                        <th  colspan ="3" class="text-center"><small>EDUCACIÓN RELIGIOSA</small></th>
                        <th colspan ="3" class="text-center"><small>EDUCACIÓN FÍSICA</small></th>
                        <th colspan ="3" class="text-center"><small>ÉTICA Y VALORES</small></th>
                        <th colspan ="3" class="text-center"><small>TECNOLOGÍA E INFORMÁTICA</small></th>
                        <th colspan ="3" class="text-center"><small>VALORACIÓN</small></th>
                    </tr>

                    <tr>
                        <th  colspan="4" class="text-center"></th>
                       

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                         <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                         <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">N</th>
                        <th class="text-center">E</th>
                        <th class="text-center">F</th>

                        <th class="text-center">PM</th>
                        <th class="text-center">PSTO</th>
                        <th class="text-center">FT</th>
                       
         
                    </tr>
                </thead>

                <tbody>  ';
// AQUÍ VA LA MATERIA MATEMATICAS
   $arrayP= array();
   $arrayZ= array();

for ($i=0; $i <$cuenta->cuenta ; $i++) { 
    $arrayZ[$i]=$i+1;
}



for ($i=0; $i <$cuenta->cuenta ; $i++) { 
    $html.=' <tr><td class="text-center">'.($i+1).'</td> ';

   

    /* VARIABLES TEMPORALES PARA GUARDAR LOS PROMEDIOS */

    $notaMatematicas = round(($listaNotasM1[$i]->notaFinal + $listaNotasM2[$i]->notaFinal + 
    $listaNotasM3[$i]->notaFinal + $listaNotasM4[$i]->notaFinal )/4,2);

    $notaCastellana = round(($listaNotasL1[$i]->notaFinal + $listaNotasL2[$i]->notaFinal + 
    $listaNotasL3[$i]->notaFinal + $listaNotasL4[$i]->notaFinal )/4,2);

    $notaIngles = round(($listaNotasI1[$i]->notaFinal + $listaNotasI2[$i]->notaFinal + 
    $listaNotasI3[$i]->notaFinal + $listaNotasI4[$i]->notaFinal )/4,2);

    $notaSociales = round(($listaNotasS1[$i]->notaFinal + $listaNotasS2[$i]->notaFinal + 
    $listaNotasS3[$i]->notaFinal + $listaNotasS4[$i]->notaFinal )/4,2);

    $notaNaturales = round(($listaNotasN1[$i]->notaFinal + $listaNotasN2[$i]->notaFinal + 
    $listaNotasN3[$i]->notaFinal + $listaNotasN4[$i]->notaFinal )/4,2);

    $notaArtistica = round(($listaNotasA1[$i]->notaFinal + $listaNotasA2[$i]->notaFinal + 
    $listaNotasA3[$i]->notaFinal + $listaNotasA4[$i]->notaFinal )/4,2);

    $notaReligiosa= round(($listaNotasR1[$i]->notaFinal + $listaNotasR2[$i]->notaFinal + 
    $listaNotasR3[$i]->notaFinal + $listaNotasR4[$i]->notaFinal )/4,2);

    $notaFisica = round(($listaNotasF1[$i]->notaFinal + $listaNotasF2[$i]->notaFinal + 
    $listaNotasF3[$i]->notaFinal + $listaNotasF4[$i]->notaFinal )/4,2);

    $notaCastellana = round(($listaNotasL1[$i]->notaFinal + $listaNotasL2[$i]->notaFinal + 
    $listaNotasL3[$i]->notaFinal + $listaNotasL4[$i]->notaFinal )/4,2);

    $notaEtica = round(($listaNotasE1[$i]->notaFinal + $listaNotasE2[$i]->notaFinal + 
    $listaNotasE3[$i]->notaFinal + $listaNotasE4[$i]->notaFinal )/4,2);

    $notaTecnologia = round(($listaNotasT1[$i]->notaFinal + $listaNotasT2[$i]->notaFinal + 
    $listaNotasT3[$i]->notaFinal + $listaNotasT4[$i]->notaFinal )/4,2);

    /* SUMARIAZACION DE FALTAS*/

     $faltaMatematicas = $listaNotasM1[$i]->faltas + $listaNotasM2[$i]->faltas + 
    $listaNotasM3[$i]->faltas + $listaNotasM4[$i]->faltas ;

    $faltaCastellana = $listaNotasL1[$i]->faltas + $listaNotasL2[$i]->faltas + 
    $listaNotasL3[$i]->faltas + $listaNotasL4[$i]->faltas ;

    $faltaIngles = $listaNotasI1[$i]->faltas + $listaNotasI2[$i]->faltas + 
    $listaNotasI3[$i]->faltas + $listaNotasI4[$i]->faltas ;

    $faltaSociales = $listaNotasS1[$i]->faltas + $listaNotasS2[$i]->faltas + 
    $listaNotasS3[$i]->faltas + $listaNotasS4[$i]->faltas ;

    $faltaNaturales = $listaNotasN1[$i]->faltas + $listaNotasN2[$i]->faltas + 
    $listaNotasN3[$i]->faltas + $listaNotasN4[$i]->faltas ;

    $faltaArtistica = $listaNotasA1[$i]->faltas + $listaNotasA2[$i]->faltas + 
    $listaNotasA3[$i]->faltas + $listaNotasA4[$i]->faltas ;

    $faltaReligiosa= $listaNotasR1[$i]->faltas + $listaNotasR2[$i]->faltas + 
    $listaNotasR3[$i]->faltas + $listaNotasR4[$i]->faltas ;

    $faltaFisica = $listaNotasF1[$i]->faltas + $listaNotasF2[$i]->faltas + 
    $listaNotasF3[$i]->faltas + $listaNotasF4[$i]->faltas;

    $faltaCastellana = $listaNotasL1[$i]->faltas + $listaNotasL2[$i]->faltas + 
    $listaNotasL3[$i]->faltas + $listaNotasL4[$i]->faltas ;

    $faltaEtica = $listaNotasE1[$i]->faltas + $listaNotasE2[$i]->faltas + 
    $listaNotasE3[$i]->faltas + $listaNotasE4[$i]->faltas ;

    $faltaTecnologia = $listaNotasT1[$i]->faltas + $listaNotasT2[$i]->faltas + 
    $listaNotasT3[$i]->faltas + $listaNotasT4[$i]->faltas;

    



     $nF=$notaMatematicas;
    if($nF>=0 and $nF <=2.9){

        $escala="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escala="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escala="A"; 
    }else{

      $escala="S"; 
    }

     $nF = $notaCastellana;
    if($nF>=0 and $nF <=2.9){

        $escalaL="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaL="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaL="A"; 
    }else{

      $escalaL="S"; 
    }

    ////////////////

      $nF = $notaIngles;
    if($nF>=0 and $nF <=2.9){

        $escalaI="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaI="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaI="A"; 
    }else{

      $escalaI="S"; 
    }

////////////// 
    $nF = $notaSociales;
    if($nF>=0 and $nF <=2.9){

        $escalaS="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaS="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaS="A"; 
    }else{

      $escalaS="S"; 
    }

    ////////////// 
    $nF = $notaNaturales;
    if($nF>=0 and $nF <=2.9){

        $escalaN="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaN="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaN="A"; 
    }else{

      $escalaN="S"; 
    }

    ////////////// 
    $nF = $notaArtistica;
    if($nF>=0 and $nF <=2.9){

        $escalaA="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaA="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaA="A"; 
    }else{

      $escalaA="S"; 
    }

    ////////////// 
    $nF = $notaReligiosa;
    if($nF>=0 and $nF <=2.9){

        $escalaR="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaR="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaR="A"; 
    }else{

      $escalaR="S"; 
    }

      ////////////// 
    $nF = $notaFisica;
    if($nF>=0 and $nF <=2.9){

        $escalaF="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaF="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaF="A"; 
    }else{

      $escalaF="S"; 
    }

    $nF = $notaEtica;
    if($nF>=0 and $nF <=2.9){

        $escalaE="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaE="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaE="A"; 
    }else{

      $escalaE="S"; 
    }

      ////////////// 
    $nF = $notaTecnologia;
    if($nF>=0 and $nF <=2.9){

        $escalaT="B-";
    }elseif($nF>2.9 and $nF <=3.8){

       $escalaT="B+"; 
    }
    elseif($nF>3.9 and $nF <=4.5){

       $escalaT="A"; 
    }else{

      $escalaT="S"; 


    
    }




$html.=' <td class="text-center">'.$listaNotasM1[$i]->nombre.'</td> ';
$html.=' <td class="text-center">'.$listaNotasM1[$i]->apellido.'</td> ';
$html.=' <td class="text-center">'.$listaNotasM1[$i]->identidadAl.'</td> '; 

$html.=' <td class="text-center">'.$notaMatematicas.'</td> '; 
$html.=' <td class="text-center">'.$escala .'</td> '; 
$html.=' <td class="text-center">'.$faltaMatematicas.'</td> '; 

$html.=' <td class="text-center">'.$notaCastellana.'</td> '; 
$html.=' <td class="text-center">'.$escalaL .'</td> '; 
$html.=' <td class="text-center">'.$faltaCastellana.'</td> '; 

$html.=' <td class="text-center">'.$notaIngles.'</td> '; 
$html.=' <td class="text-center">'.$escalaI .'</td> '; 
$html.=' <td class="text-center">'.$faltaIngles.'</td> '; 

$html.=' <td class="text-center">'.$notaSociales.'</td> '; 
$html.=' <td class="text-center">'.$escalaS .'</td> '; 
$html.=' <td class="text-center">'.$faltaSociales.'</td> '; 

$html.=' <td class="text-center">'.$notaNaturales.'</td> '; 
$html.=' <td class="text-center">'.$escalaN .'</td> '; 
$html.=' <td class="text-center">'.$faltaNaturales.'</td> '; 

$html.=' <td class="text-center">'.$notaArtistica.'</td> '; 
$html.=' <td class="text-center">'.$escalaA .'</td> '; 
$html.=' <td class="text-center">'.$faltaArtistica.'</td> '; 

$html.=' <td class="text-center">'.$notaReligiosa.'</td> '; 
$html.=' <td class="text-center">'.$escalaR .'</td> '; 
$html.=' <td class="text-center">'.$faltaReligiosa.'</td> '; 

$html.=' <td class="text-center">'.$notaFisica.'</td> '; 
$html.=' <td class="text-center">'.$escalaF .'</td> '; 
$html.=' <td class="text-center">'.$faltaFisica.'</td>'; 

$html.=' <td class="text-center">'.$notaEtica.'</td> '; 
$html.=' <td class="text-center">'.$escalaE .'</td> '; 
$html.=' <td class="text-center">'.$faltaEtica.'</td>'; 
 
$html.=' <td class="text-center">'.$notaTecnologia.'</td> '; 
$html.=' <td class="text-center">'.$escalaT .'</td> '; 
$html.=' <td class="text-center">'.$faltaTecnologia.'</td>'; 

// Código para calcular promedio

$promedioP = $notaMatematicas + $notaCastellana + $notaIngles + $notaSociales + $notaNaturales + $notaArtistica 
+ $notaReligiosa + $notaFisica + $notaEtica+ $notaTecnologia;


$promedioF=$promedioP/10;

$faltasTotales = $faltaMatematicas + $faltaCastellana + $faltaIngles + $faltaSociales + $faltaNaturales
                + $faltaArtistica + $faltaReligiosa + $faltaFisica + $faltaEtica + $faltaTecnologia;


$html.=' <td class="text-center" >'.round($promedioF,2) .'</td> '; 

 
 $html.=' <td class="text-center">'.$arrayZ[$i].'</td>';

 $html.=' <td class="text-center">'.$faltasTotales.'</td></tr>';

} 

               


                $html.='
                    

                </tbody>
            </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">S = SUPERIOR</th>
                        <th class="text-center">A = ALTO</th>
                        <th class="text-center">B+ = BÁSICO</th>
                        <th class="text-center">B- = BAJO</th>
                    </tr>
                </thead>
             </table>

                </table>
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">N= NOTA FINAL</th>
                        <th class="text-center">E = ESCALA NACIONAL</th>
                        <th class="text-center">F = FALTAS</th>
                        <th class="text-center">PM = PROMEDIO </th>
                    </tr>


                </thead>
             </table>
        </div>
    </div>
</div>

<br />

<!-- /. Firmas -->
<div class="row text-center">
    <div class="col-lg-12">
        ________________________________
        <b> <br /> Test rector<br />Rector(a)</b>
    </div>
</div>

<br />';

//}
Load::lib('mpdf');

    $mpdf = new mPDF('utf-8', array(330,216));
    $mpdf->debug = true;
    
$html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');

    $mpdf->WriteHTML($css, 1);
    $mpdf->WriteHTML($html);
    $mpdf->Output('informeFinal.pdf', 'I');
    exit;
?>