<?php View::content(); ?>

<?php echo Form::open(); // por defecto llama a la misma url ?>

<?php 

if(intval($gradoS)==13){

 $gradoL="PREESCOLAR";
}elseif(intval($gradoS)==1){

$gradoL="PRIMERO";
}elseif(intval($gradoS)==2){

$gradoL="SEGUNDO";
}elseif(intval($gradoS)==3){

$gradoL="TERCERO";
}elseif(intval($gradoS)==4){

$gradoL="CUARTO";
}elseif(intval($gradoS)==5){

$gradoL="QUINTO";
}elseif(intval($gradoS)==6){

$gradoL="SEXTO";
}elseif(intval($gradoS)==7){

$gradoL="SÉPTIMO";
}elseif(intval($gradoS)==8){

$gradoL="OCTAVO";
}elseif(intval($gradoS)==9){

$gradoL="NOVEMO";
}elseif(intval($gradoS)==10){

$gradoL="DÉCIMO";
}else {

  $gradoL="UNDÉCIMO";
}


?>

<div class="row">

<div class="col-lg-3">

<div class="form-group">
  <label for="oldTeacher">Grado a Asignar:</label>
  <input type="text" class="form-control" id="usr" value ="<?php echo $gradoL; ?>" disabled> 
</div>

</div>

<div class="col-lg-4">

    <div class="form-group">
            <label>Escoger profesor(a) de grado completo</label>
            <select class="form-control" name ="idPro" id="idPro">
             <optgroup label="Seleccione el nuevo profesor">
              <?php foreach ($profesor->items as $item) : ?>
                <option value='<?php echo $item->idPro ?>'> <?php echo $item->nombrePro ?> &nbsp;<?php echo $item->apellidoPro ?> </option>
              <?php endforeach; ?>
              </optgroup>
            </select>
        </div>  

         <div class="form-group" style="display:none;">
            <input type="text" name="idGrado" id="idGrado"  value ="<?php echo $gradoS; ?>" class="form-control" >
             </div>
</div>



</div>
<!-- /.row -->

<div class="row">

    <div class="col-lg-2">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Actualizar">Asignar a grado actual
            <!--?php echo Form::submit('Actualizar') ?-->
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions">
            <?= Html::link("materia/listar", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

<?php echo Form::close() ?>
