<?php View::content(); ?>

<?php echo Form::open("materia/create"); ?>

<div class="row">

    <div class="col-lg-3">
        <div class="form-group">
            <input type="text" name="idMateria" id="idMateria" class="form-control" placeholder="Identificador">
        </div>
        <div class="form-group">
            <input type="text" name="nombre"  id="nombre" class="form-control" placeholder="Nombre">
        </div>
        <div class="form-group">
            <label>Comentario</label>
            <textarea name="comentario" class="form-control" rows="3"></textarea>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="form-group">
            <input type="text" name="grado"  id="grado" class="form-control" placeholder="Grado">
        </div>
        <div class="form-group">
            <input type="text" name="grupo"  id="grupo" class="form-control" placeholder="Grupo">
        </div>
    </div>

</div>
<!-- /.row -->

<div class="row">

    <div class="col-lg-1">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar">Agregar
            <!--?php echo Form::submit("Ingresar","class: boton"); ?-->	
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

<?php echo Form::close(); ?>


