<!-- /.row -->
<?php View::content(); ?>

<div class="row">
<div class="col-lg-2">
        <div class="actions">
            <?= Html::link("materia/index", 'Menú Principal', 'class="btn btn-success"') ?>
        </div>
    </div>
    

    <div class="col-lg-2">
        <div class="actions">
            <?= Html::link("materia/asignar", 'Asignar profesor a grado completo', 'class="btn btn-info"') ?>
        </div>
    </div>
    </div>
    </div>

<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <br />
                <thead>
                    <tr>
                        <th>Número</th>
                        <th>ID</th>
                        <th>Nombre Materia</th>
                        <th>Grado</th>
                        <th>Nombre P.A</th>
                        <th>Apellido P.A</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                   
                    <?php

                    
                 
                     for($i=0; $i<count($listaMaterias); $i++) {

                     ?>
                    <tr>
                        <td><?php echo $i ?></td>  
                        <td><?php echo $listaMaterias[$i]->idMateria ?></td>  
                         <td><?php echo $listaMaterias[$i]->nombreMateria ?></td>  
                          <td><?php echo $listaMaterias[$i]->gradoMateria ?></td>  
                          <td><?php echo $listaMaterias[$i]->nombrePro ?></td>
                          <td><?php echo $listaMaterias[$i]->apellidoPro ?></td>          
                     
                   
                      
                        <td>
                        <?php $idM = $listaMaterias[$i]->idMateria?>
                         <?php $n = $listaMaterias[$i]->nombrePro?>

                          <?php $a = $listaMaterias[$i]->apellidoPro?>


                       <i class="fa fa-fw fa-edit"></i><?php echo Html::linkAction("edit/$idM/$n/$a", ' Cambiar Profesor') ?>
                            
                        </td>
                    </tr>
                    <?php }?>
                </tbody>
            </table>
        </div>
    </div>
</div>