<?php View::content(); ?>


<div class="row">

    <div class="col-lg-3">
        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open("boletin/buscar/"); ?>
               <h4>Nombre</h4>
                <input type="hidden" name="valN" id ="valN" value="2">
                <input type="text" name="nombreP" id ="nombreP" class="form-control" placeholder="Introducir Nombre" required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>
    </div>



     <div class="col-lg-3" style ="margin-left:30px;">
        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open("boletin/buscar/"); ?>
               <h4>Apellido</h4>
                <input type="hidden" name="valA" id ="valA" value="2">
                <input type="text" name="apellidoP" id ="apellidoP" class="form-control" placeholder="Introducir Apellido" required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>
    </div>



     <div class="col-lg-3" style ="margin-left:30px;">
        <div class="form-group input-group">
            <span class="input-group-btn">
                <?php echo Form::open("boletin/buscar/"); ?>
               <h4>Documento ID </h4>
                <input type="hidden" name="valI" id ="valI" value="2">
                <input type="number" name="cedulaP" id ="cedulaP" class="form-control" placeholder="Introducir Documento " required>
                <button class="btn btn-default" type="submit" name="Buscar"><i class="fa fa-search"></i></button>
                <?php echo Form::close(); ?>
            </span>
        </div>
    </div>


</div>


<div class="row">

    <div class="col-lg-12">
        <div class="table-responsive">     
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                        <th>#</th>
                        <th>Documento</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Genero</th>
                        <th>RH</th>
                        <th>Grado</th>
                        <th>Estado</th>
                        <th>Matricula</th>
                        
                      
                        <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                         <?php for($i=0; $i<count($listaAlumnos); $i++) { ?>
                            <tr>
                                <td><?php echo $i ?></td>    
                                <td><?php echo $listaAlumnos[$i]->identidadAl ?></td>
                                <td><?php echo $listaAlumnos[$i]->nombre ?></td>
                                <td><?php echo $listaAlumnos[$i]->apellido ?></td>
                                <td><?php echo $listaAlumnos[$i]->genero ?></td>
                                <td><?php echo $listaAlumnos[$i]->rh ?></td>
                                <td><?php echo $listaAlumnos[$i]->nombreGrado ?></td>
                                <td><?php echo $listaAlumnos[$i]->tipoEstado ?></td>
                                <td><?php echo $listaAlumnos[$i]->estadoMatricula ?></td>
                              
                               
                                <td>
                                   <?php  $temp=intval($listaAlumnos[$i]->idAlumno); ?>
                                    <i class="fa fa-fw fa-edit"></i><?php echo Html::linkAction("soloBoletin/$temp/", ' Generar Boletin') ?>
                                   
                                </td>
                            </tr>
                             <?php } ?>
                        </tbody>
                    </table>
                     
            
        </div>
    </div>
</div>
<!-- /.row -->

<div class="row">

    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->
