<?php View::content(); ?>

<?php echo Form::open("boletin/listar"); ?>

<div class="row">

  <div class="col-lg-10">

    <div class="panel panel-warning">
     <div class="panel-heading">Información Importante</div>
     <div class="panel-body">Para un boletín individual, es necesario que escoga el grado y el periodo.<br> Luego de esto, 

        solo imprima la hoja correspondiente al estudiante.
        
        <hr>
        Nota: Si no sabe el curso del estudiante, vaya a la sección de "Gestionar Alumnos" y luego busque por nombre,apellido o documento.
        
     </div>
   </div>

 </div>  

</div> <!-- Fin Header Row 1-->


<div class="row">

   <div class="col-lg-1">
       

  <h4>Año</h4>

  <div class="form-group">
    <input  name="idAnio" id="idAnio" class="form-control" value="<?php echo $_SESSION['globalYear']; ?>" disabled>
</div>
</div>

<div class="col-lg-2">


    <div class="form-group" style="display:none;">
        <input type="text" name="gradoN" id="gradoN" class="form-control" placeholder="Grado" value="2">
    </div>

    <div class="form-group" style="display:none;">
        <input type="number" name="idAnio2" id="idAnio2" class="form-control"  value="<?php echo $_SESSION['globalYear']; ?>">
    </div>

    <h4>Seleccionar grado</h4>

    <div class="form-group">
        <select class="form-control"  name ="gradoF" id="gradoF" >>
            <optgroup label="Grados">
                <option value ="13">Preescolar</option>
                <option value ="1">1</option>
                <option value ="2">2</option>
                <option value ="3">3</option>
                <option value ="4">4</option>
                <option value ="5">5</option>
                <option value ="6">6</option>
                <option value ="7">7</option>
                <option value ="8">8</option>
                <option value ="9">9</option>
                <option value ="10">10</option>
                <option value ="11">11</option>
            </optgroup>
        </select>


    </div>
</div>

<div class="col-lg-2">
   <h4>Periodo</h4>

   <div class="form-group">
   <select class="form-control"  name ="periodoA" id="periodoA" >
       <optgroup label="Periodos">
        <option value ="1" selected >1</option>
        <option value ="2" >2</option>
        <option value ="3" >3</option>
        <option value ="4" >4</option>

    </optgroup>
</select>

</div><!--periodo-->


</div>



 <div class="col-lg-3" >
        <button  style ="margin-top:38px;" class="btn btn-success waves-effect waves-light" type="submit" name="generar"  >Siguiente paso
            <!--?php echo Form::submit("Ingresar","class: boton"); ?--> 
        </button>
    </div>




</div>
<!-- /.row -->

<div class="row">

   


</div>
<!-- /.row -->

<?php echo Form::close(); ?>