<?php View::content(); 

?>

<?php echo Form::open("boletin/porGrados/"); ?>

<div class="row">

  <div class="col-lg-12">

    <div class="panel panel-primary">
     <div class="panel-heading"># de estudiantes</div>
     <div class="panel-body">En este momento hay <b><?php $limite=$number->cuenta; echo $number->cuenta;?> </b>estudiantes en este curso</div>
   </div>

 </div>  

</div> <!-- Fin Header Row 1-->


<div class="row">

  <div class="col-lg-3">

    <div class="form-group">
      <label>Nombre Rector(a)</label>

      <input type="text" name="rectorName" id="rectorName" class="form-control" value="<?php echo $anio->anioRectora; ?>" disabled>

    </div>
    <div class="form-group" style="display:none;">
      <input  name="rectorNameF" id="rectorNameF" class="form-control"  value="<?php echo $anio->anioRectora; ?>">
    </div>

  </div>
  <div class="col-lg-3">

  <div class="form-group">
            <label>Seleccionar director de grado</label>
            <select class="form-control" name ="idPro" id="idPro">
             <optgroup label="Seleccione el nuevo profesor">
              <?php foreach ($profesor->items as $item) : ?>
                <option value='<?php echo $item->idPro ?>'> <?php echo $item->nombrePro ?> &nbsp; <?php echo $item->apellidoPro ?> </option>
              <?php endforeach; ?>
              </optgroup>
            </select>
        </div>  

   <div class="form-group" style="display:none;">
    <input type="number" name="limite" id="limite" class="form-control"  value="<?php echo $limite; ?>">
  </div>


</div>

</div> <!-- Fin Row 1 -->


<div class="row">

  <div class="col-lg-2">
    <button class="btn btn-success waves-effect waves-light" type="submit" name="Ingresar" >Generar Boletines
      <!--?php echo Form::submit("Ingresar","class: boton"); ?--> 
    </button>
  </div>
  <div class="col-lg-1">
    <div class="actions">
      <?= Html::linkAction("index/", 'Volver', 'class="btn btn-danger"') ?>
    </div>
  </div>

</div>
<hr>
<!-- /.row -->
<div class="row">

  <div class="col-lg-12">
    <div class="table-responsive">     
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Documento</th>
            <th>Nombres</th>
            <th>Apellidos</th>

            <th class ="info">Grado</th>
            <th>Estado</th>
            <th>Matricula</th>


          </tr>
        </thead>
        <tbody>
         <?php for($i=0; $i<count($listaAlumnos); $i++) { ?>
         <tr>
          <td><?php echo ($i+1) ?></td>    
          <td><?php echo $listaAlumnos[$i]->identidadAl ?></td>
          <td><?php echo $listaAlumnos[$i]->nombre ?></td>
          <td><?php echo $listaAlumnos[$i]->apellido ?></td>

          <td><?php echo $listaAlumnos[$i]->nombreGrado ?></td>
          <td><?php echo $listaAlumnos[$i]->tipoEstado ?></td>
          <td><?php echo $listaAlumnos[$i]->estadoMatricula ?></td>

          <?php 


         

          ?>

        </tr>
        <?php } ?>
      </tbody>
    </table>


  </div>
</div>
</div>
<!-- /.row -->

<?php echo Form::close(); ?>
