<?php View::content(); ?>
<?php
for($i=0; $i<count($matricula2); $i++){

   

     $estadoMatricula=$matricula2[$i]->estadoMatricula;

     $anioMatricula=$matricula2[$i]->anio_idAnio;
    

   
}

?>



<?php echo Form::open(); ?>

<div class="row">
<h4 style="margin-left:15px; color:#3f51b5">Datos estudiante (Obligatorios)</h4>
 <div class="col-lg-3">

  <div class="form-group">
    <label for="identificación">Identificación Alumno:</label>
    <input type="number" class="form-control" id="identificacion" name ="identificacion" required value ="<?php echo $alumno->identidadAl ?>" >
    <input type="hidden" id="idAl" name ="idAl" value ="<?php echo $idAl; ?>" >
  </div>  



 <div class="form-group">
        <label for="nomF">Nombres</label>

         <input type="text" name="nomF" id="nomF" class="form-control" value="<?php echo $alumno->nombre; ?>" placeholder="Nombres" required >

 </div>

 <div class="form-group">
    <label for ="apeF">Apellidos</label>

     <input type="text" name="apeF" id="apeF" class="form-control" value="<?php echo $alumno->apellido; ?>" placeholder="Apellidos" required >

 </div>

  <div class="form-group">
            <label for ="estadoF">Estado</label> 
            <select class="form-control" name ="estadoF" id ="estadoF">

            <?php $array = array();
            if ($alumno->estado_idEstado == 1) $array[0] = 'selected'; else $array[0] = '';
            if ($alumno->estado_idEstado == 2) $array[1] = 'selected'; else $array[1] = '';

             ?>
                <option value="1" <?= $array[0] ?> >Activo</option>
                <option value="2" <?= $array[1] ?> >Inactivo</option>
            </select>
  </div>


 


</div><!-- FIN COLUMNA 1 ***************************************-->

<div class="col-lg-3">



        <div class="form-group">
            <label for ="edadF">Fecha de Nacimiento</label>
    <input type="date"  name="edadF" id="edadF" class="form-control"  value='<?php echo $alumno->nacimiento; ?>' required >
        </div>


        <div class="form-group">
          <?php $array = array();
            if ($alumno->genero == 'M') $array[0] = 'selected'; else $array[0] = '';
            if ($alumno->genero == 'F') $array[1] = 'selected'; else $array[1] = '';

             ?>
            <label for ="generoF">Género</label>
            <select class="form-control"  name ="generoF"id="generoF">

                <option value ="M" <?= $array[0] ?> >Masculino</option>
                <option value ="F" <?= $array[1] ?> >Femenino</option>
            </select>
        </div>

          <div class="form-group">
            <label for="dirF">Dirección</label>
            <input type="text" name="dirF" id="dirF" class="form-control" value="<?php echo $alumno->dir; ?>" placeholder="Dirección" required>
        </div>


        <div class="form-group">
            <label for="celF">Celular (No Obligatorio)</label>
            <input type="number" value="<?php echo $alumno->celular; ?>"  maxlength="10" size="10" name="celF" id="celF" class="form-control"  placeholder="Celular" >
        </div>


<!-- INSERT CODE HERE -->

</div><!-- FIN COLUMNA 22222222222222222 ***************************************-->

 <div class="col-lg-3">

<div class="form-group">


        <?php $array = array();
            if ($alumno->rh == 'O+') $array[0] = 'selected'; else $array[0] = '';
            if ($alumno->rh == 'O-') $array[1] = 'selected'; else $array[1] = '';
            if ($alumno->rh == 'A+') $array[2] = 'selected'; else $array[2] = '';
            if ($alumno->rh == 'A-') $array[3] = 'selected'; else $array[3] = '';
            if ($alumno->rh == 'B+') $array[4] = 'selected'; else $array[4] = '';
            if ($alumno->rh == 'B-') $array[5] = 'selected'; else $array[5] = '';
            if ($alumno->rh == 'AB+') $array[6] = 'selected'; else $array[6] = '';
            if ($alumno->rh == 'AB-') $array[7] = 'selected'; else $array[7] = '';
        ?>
            <label for ="rhF">RH</label> 
            <select class="form-control" name ="rhF" id ="rhF">
                <option value ="O+" <?= $array[0] ?> >O+</option>
                <option  value ="O-" <?= $array[1] ?> >O-</option>
                <option  value ="A+" <?= $array[2] ?> >A+</option>
                <option  value ="A-" <?= $array[3] ?> >A-</option>
                <option  value ="B+" <?= $array[4] ?> >B+</option>
                <option  value ="B-" <?= $array[5] ?> >B-</option>
                <option  value ="AB+" <?= $array[6] ?> >AB+</option>
                <option  value ="AB-" <?= $array[7] ?> >AB-</option>
            </select>
        </div>


        <div class="form-group">
            <label for ="idAcuF">Grado Actual</label>
            <input type="text"  value="<?php echo $matriculaFinal->nombreGrado; ?>" 
            class="form-control" disabled>

        </div>
     






</div><!-- FIN COLUMNA 33333333333333333 ***************************************-->

<div class="col-lg-3">
<div class="form-group">
            <label for ="idAcuF">Cédula o TI (A)</label>

            <input type="number"  maxlength="15" name ="idAcuF" id ="idAcuF" value="<?php echo $alumno->cedulaAcu; ?>" class="form-control" placeholder=" CC Acudiente" required>

        </div>

        <div class="form-group">
            <label for ="nomAcuF">Nombre Completo (A)</label>

            <input type="text"   name="nomAcuF" id="nomAcuF"  value="<?php echo $alumno->nombreAcu; ?>" class="form-control" placeholder="Nombre Completo" required>

        </div>




        <div class="form-group">
            <label for ="dirAcuF">Dirección (A)</label>

            <input type="text" name="dirAcuF" id="dirAcuF" class="form-control" value="<?php echo $alumno->dirAcu; ?>" placeholder="Dirección Acudiente" required>

        </div>
        <div class="form-group">
            <label for ="celAcuF">Celular (A)</label>

            <input type="number"  maxlength="10" size="10" name="celAcuF" id="celAcuF" value="<?php echo $alumno->celAcu; ?>" class="form-control"  placeholder="Celular Acudiente" >

        </div>



</div><!-- FIN COLUMNA 444444444444444444 ***************************************-->


</div><!-- FIN FILA FORMULARIOOOOOOOOOOOOOOOOOO 1 *************************************** NO TOCAR--> 

<hr style="border-color:#2196f3">

<h4 style="color:#3f51b5">Tipo de matrícula y sede (Importante)</h4>

    <div class="row">

        <div class="col-lg-4">

            
          <div class="form-group">
            <label for ="idAcuF">Matricula Actual</label>
            <input type="text"  value="<?php $var="-"; echo $estadoMatricula . $var . $anioMatricula;  ?>" class="form-control"  disabled>
          </div>

          <?php 


        ?>

          <div class="bg-danger">
                <div class="form-group">
                     <label for="tipoMatF">Cambiar matricula a:</label> 

                      <?php 
                $array = array();
            if ($matriculaFinal->estadoMatricula == 'Inicial') $array[0] = 'selected'; else $array[0] = '';
            if ($matriculaFinal->estadoMatricula == 'Extraordinaria') $array[1] = 'selected'; else $array[1] = '';
            if ($matriculaFinal->estadoMatricula == 'Trasladado') $array[2] = 'selected'; else $array[2] = '';
            if ($matriculaFinal->estadoMatricula == 'Desertor') $array[3] = 'selected'; else $array[3] = '';

                  /* Necesito el año global y el número para sacar el id*/
            ?>
           
                         <select class="form-control" name ="tipoU" id="tipoU">

            <option value='1' <?= $array[0] ?>>Inicial </option>
            <option value='2' <?= $array[1] ?>>Extraordinaria </option>
            <option value='3' <?= $array[2] ?>>Trasladado(a) </option>
            <option value='4' <?= $array[3] ?>>Desertor(a) </option>
                         </select>
              </div>    
        </div>   
        
        <div class="col-lg-2"></div>



        </div><!-- end col 1-->

          <div class="col-lg-4">

             <div class="form-group">
            <label for ="idAcuF">Sede Actual</label>
            <input type="text"  value="<?php echo $alumno->sede;  ?>" class="form-control"  disabled>
          </div>

          <?php 
                $array = array();
            if ($alumno->sede == 'belen') $array[0] = 'selected'; else $array[0] = '';
            if ($alumno->sede == 'bellavista') $array[1] = 'selected'; else $array[1] = '';
            if ($alumno->sede == 'florida') $array[2] = 'selected'; else $array[2] = '';
            if ($alumno->sede == 'marqueza') $array[3] = 'selected'; else $array[3] = '';
            if ($alumno->sede == 'lorenzo') $array[4] = 'selected'; else $array[4] = '';

            ?>

          <div class="bg-danger">
                <div class="form-group">
                     <label for="tipoMatF">Cambiar sede a:</label> 
           
                         <select class="form-control" name ="sedeU" id="sedeU">
                                    <option value='belen' <?= $array[0] ?> >Belén(Principal) </option>
                                            <option value='bellavista' <?= $array[1] ?> >Bellavista </option>
                                            <option value='florida' <?= $array[2] ?> >La Florida </option>
                                            <option value='marqueza' <?= $array[3] ?> >La Marqueza</option>
                                            <option value='lorenzo' <?= $array[4] ?> >San Lorenzo </option>
                         </select>
              </div>    
        </div>    

        </div><!-- end col 2-->

    </div><!--end row 2-->


<hr style="border-color:#2196f3">


    <div class="row">
    <h4 style="margin-left:15px; color:#3f51b5">Datos familiares </h4>
   <div class="col-lg-3">

      <div class="form-group">
         <label>Identificación TI-CC(Madre)</label>
         <input type="number" maxlength="15"  name="ccMadre" value="<?php echo $alumno->idMadreA; ?>" id="ccMadre" class="form-control" placeholder="Cédula Madre" >
      </div>

       <div class="form-group">
         <label>Identificación TI-CC(Padre)</label>
         <input type="number" maxlength="15"  name="ccPadre" value="<?php echo $alumno->idPadreA; ?>" id="ccPadre" class="form-control" placeholder="cédulaPadre" >
      </div>

    

   </div>
   <!-- Fin Columna 1 -->
   <div class="col-lg-3">


      <div class="form-group">
         <label>Nombres (Madre)</label>
         <input type="text" name="nombreMadre" id="nombreMadre" value="<?php echo $alumno->madreNombreA; ?>"  class="form-control" placeholder="Nombres Madre" >
      </div>

      <div class="form-group">
         <label>Nombres (Padre)</label>
         <input type="text"  name="nombrePadre" id="nombrePadre"  value="<?php echo $alumno->padreNombreA; ?>" class="form-control" placeholder="Nombres Padre">
      </div>
   </div>
   <!-- Fin Columna 2 -->
   <div class="col-lg-3">
      <div class="form-group">
         <label>Apellidos (Madre)</label>
         <input type="text" name="apellidoMadre" id="apellidoMadre" value="<?php echo $alumno->madreApellidoA; ?>"  class="form-control" placeholder="Apellidos Madre" >
      </div>

      <div class="form-group">
         <label>Apellidos (Padre)</label>
         <input type="text"  name="apellidoPadre" id="apellidoPadre" value="<?php echo $alumno->padreApellidoA; ?>"  class="form-control" placeholder="Apellidos Padre" >
      </div>
      
   </div>
   <!-- Fin Columna 3-->
   <!-- Columna 4-->
   <div class="col-lg-3">
      <div class="form-group">
         <label>Celular(Madre)</label>
         <input type="number"  maxlength="15" name ="celMadre" id ="celMadre" value="<?php echo $alumno->celMadreA; ?>" class="form-control" placeholder=" Celular Madre" >
      </div>
  <div class="form-group">
         <label>Celular(Padre)</label>
         <input type="number"  maxlength="15" name ="celPadre" id ="celPadre" value="<?php echo $alumno->celPadreA; ?>"  class="form-control" placeholder=" Celular Padre" >
      </div>
     
      
     
   </div>
   
   <!-- Fin Columna 4-->
</div>


<hr style="border-color:#2196f3">


<div class="row"> <!-- INICIO BOTÓN ACCIONES **********************************-->

    <div class="col-lg-1">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Actualizar Alumno">Actualizar
            
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

<?php echo Form::close(); ?>