<?php View::content(); ?>
<?php $space= "&nbsp;";?>
<?php echo Form::open(); // por defecto llama a la misma url ?>

<div class="row">

  <div class="col-lg-12">

    <div class="panel panel-primary">
     <div class="panel-heading">Datos del actual logro:</div>
     <div class="panel-body">Materia: <b> <?php echo $materia->nombreMateria; ?> <?php echo $space; ?> </b> Grado:<b> <?php echo $materia->gradoMateria; ?><?php echo $space; ?></b> Profesor(a) actual:<b> <?php echo $profesor->nombrePro.$space.$profesor->apellidoPro; ?> </b></div>
   </div>

 </div>  


</div>

<div class="form-group" style="display:none;">
  <input type="text" name="periodoA" id="periodoA" class="form-control" value="2">
</div>

<!-- /.row -->
<div class="row">

<div class="col-lg-5">
 <div class="form-group">
  <label >Fortaleza</label>
  <textarea class="form-control" rows="2" id="fortalezaF" name ="fortalezaF" maxlength="120" > <?php echo $logro->fortaleza; ?></textarea>
</div>

</div>

  <div class="col-lg-5">
   <div class="form-group">
    <label >Debilidad</label>
    <textarea class="form-control" rows="2" id="debilidadF" name ="debilidadF" maxlength="120" ><?php echo $logro->debilidad; ?></textarea>
  </div>
</div>


</div>
<hr>

<div class="row">

  <div class="col-lg-2">

  </div>

  <div class="col-lg-1">

  </div>

  <div class="col-lg-2" style ="padding-left:40px;">
    <button class="btn btn-success waves-effect waves-light" type="submit" name="Actualizar">Actualizar Logro
      <!--?php echo Form::submit('Actualizar') ?-->
    </button>
  </div>


  <div class="col-lg-2" style ="padding-right:20px;">
    <div class="actions">
      <?= Html::link("logros/listar", 'Volver a lista', 'class="btn btn-info"') ?>
    </div>
  </div>

</div>
<!-- /.row -->

<?php echo Form::close() ?>
