<?php View::content(); ?>

<?php echo Form::open(); ?>


 
 <input type="hidden" name="copia"  id="copia" class="form-control" value='2' > 
       

  <hr>

<div class="row">

    <div class="col-lg-3">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Actualizar">Generar copia de seguridad
            <!--?php echo Form::submit("Ingresar","class: boton"); ?-->
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>

<hr>
<!-- /.row -->

<?php echo Form::close(); ?>