<?php View::content();  // Index Sistema?>

<h4><small>Recordamos que los <b>Años Lectivos</b> solo son editables, debido a que en ellos se enlaza información de todos los estudiantes, notas, periodos y demás.</small></h4>
<h4><small>Cuando creas el Año Lectivo automáticamente se crean <b>2 semestres</b> y los <b>4 periodos</b> correspondientes.</small></h4>


<br/>

<div class="row">
    <div class="col-lg-2">
        <div class="actions">
            <?= Html::linkAction("create/", 'Crear año lectivo', 'class="btn btn-primary"') ?>
        </div>
    </div>

    <div class="col-lg-2">
        <div class="actions">
            <?= Html::linkAction("buscar/", 'Buscar año lectivo', 'class="btn btn-info"') ?>
        </div>
    </div>
</div><!--end row-->

<hr>

<?php echo Form::open("sistema/cambiar"); ?>

<div class="row">

    <div class= "col-lg-3">
        <h4 style=" color:#3f51b5" >Cambiar año lectivo</h4>

      <div class="form-group">

      <?php $array = array();

            
            if (intval($_SESSION['globalYear']) == 2017) $array[0] = 'selected'; else $array[0] = '';
            if (intval($_SESSION['globalYear']) == 2018) $array[1] = 'selected'; else $array[1] = '';
            if (intval($_SESSION['globalYear']) == 2019) $array[2] = 'selected'; else $array[2] = '';
            if (intval($_SESSION['globalYear']) == 2020) $array[3] = 'selected'; else $array[3] = '';
            if (intval($_SESSION['globalYear']) == 2021) $array[4] = 'selected'; else $array[4] = '';
        

             ?>
        
         <select class="form-control" name ="globalYear" id ="globalYear">
            <option value="2017" <?= $array[0] ?>>2017</option>
            <option value="2018"<?= $array[1] ?>>2018</option>
            <option value="2019"<?= $array[2] ?>>2019</option>
            <option value="2018"<?= $array[3] ?>>2020</option>
            <option value="2019"<?= $array[4] ?>>2021</option>
            <option value="8888">Crear mas...</option>
         </select>
      </div>

    </div>

    <div class="col-lg-3" style="margin-top:38px;">
        
        <button class="btn btn-success waves-effect waves-light" type="submit" >Cambiar Año Lectivo
           
        </button>
    
    </div>

<?php echo Form::close(); ?>

<?php echo Form::open("sistema/cambiarSede"); ?>
 
    <div class ="col-lg-3">
        <h4 style=" color:#3f51b7" >Cambiar sede actual</h4>
    <div class="form-group">

    <?php $array = array();

                    
        if (strval($_SESSION['globalSede']) == 'belen') $array[0] = 'selected'; else $array[0] = '';
        if (strval($_SESSION['globalSede']) == 'bellavista') $array[1] = 'selected'; else $array[1] = '';
        if (strval($_SESSION['globalSede']) == 'florida') $array[2] = 'selected'; else $array[2] = '';
        if (strval($_SESSION['globalSede']) == 'marqueza') $array[3] = 'selected'; else $array[3] = '';
        if (strval($_SESSION['globalSede']) == 'lorenzo') $array[4] = 'selected'; else $array[4] = '';


 ?>
        <select class="form-control"  name ="sedeF" id="sedeF" >>
            <optgroup label="Sedes ">
                <option value ="belen" <?= $array[0] ?>>Belen (Principal)</option>
                <option value ="bellavista"<?= $array[1] ?>>Bellavista</option>
                <option value ="florida"<?= $array[2] ?>>La Florida</option>
                <option value ="marqueza"<?= $array[3] ?>>La Marqueza</option>
                <option value ="lorenzo"<?= $array[4] ?>>San Lorenzo</option>
        
            </optgroup>
        </select>


    </div>
  </div>

  
    <div class="col-lg-3" style="margin-top:38px;">
        
        <button class="btn btn-danger waves-effect waves-light" type="submit" name ="sedeButton" >Cambiar Sede Actual
           
        </button>
    
    </div>

 

</div>

<?php echo Form::close(); ?>

<!-- /.row -->

<div class="row">
    <div class="col-lg-2">
        <?php if ($listaLectivos->prev) echo Html::linkAction("index/$listaLectivos->prev/", '<< Anterior'); ?>
    </div>
    <div class="col-lg-2">
        <?php if ($listaLectivos->next) echo Html::linkAction("index/$listaLectivos->next/", 'Próximo >>'); ?>
    </div>
</div>
<!-- /.row -->

<br>

<h4 style=" color:#3f51b5">Lista de Años Lectivos Actuales</h4>
<br>
<div class="row">

    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead class="thead-inverse">
                    <tr>
                        <th>#</th>
                        <th>Año Lectivo</th>
                        <th>Rector(a)</th>
                        <th>Acciones</th>
                        
                    </tr>
                </thead>
                <tbody>
                    
                        <?php  $num=0; ?>
                    <?php foreach ($listaLectivos->items as $item) : ?>
                        <tr>

                            <td><?php echo $num; ?></td>
                            <td><?php echo $item->numeroAnio ?></td>
                             <td><?php echo $item->anioRectora ?></td>
                            <?php  $num++; ?>
                            
                            <td>
                                <i class="fa fa-fw fa-edit"></i><?php echo Html::linkAction("edit/$item->idAnio/", ' Editar Rector(a)') ?>
                               
                                
                            </td>  
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

</div>
<!-- /.row -->
