<!-- Page Acerca De -->
<div class="jumbotron">
    <h3>Academic </h3>
    <h4>Tutorial
		<a href="<?php echo PUBLIC_PATH ?>ManualUsuarioAcademic.pdf" >Descargar Tutorial en PDF</a>
    </h4>

    <h4>Si encuentra algún problema por favor contactarse al siguiente correo electónico :</h4>
   
        
        
        <h4 style="color:#00BFFF;">yecaicedo@unicauca.edu.co</h4>
        <h4>Whatsapp: 312 666 5895</h4>
        <h4>Versión Actual de Academic: 1.0</h4>
        
        <h4>Año: 2018</h4>
         <br />
    </p>
</div>
