<?php View::content(); ?>

<?php echo Form::open(); ?>

<div class="row">

    <div class="col-lg-3">

        <div class="form-group">
            <label>Nombres</label>
            <input type="text" name="nombresF"  id="nombresF" class="form-control" value='<?php echo $profesor->nombrePro; ?>' > 
            <input type="hidden" name="idPro"  id="idPro" class="form-control" value='<?php echo $profesor->idPro; ?>' > 
        </div>
        <div class="form-group">
            <label>Apellidos</label>
            <input type="text" name="apellidosF"  id="apellidosF" class="form-control" value='<?php echo $profesor->apellidoPro; ?>' >
        </div>
        <div class="form-group">
            <label>Identificación</label>
            <input type="number" name="idF"  id="idF" class="form-control" value='<?php echo $profesor->identidadPro; ?>'>
        </div>   
        
       <div class="form-group">
            <select class="form-control"  name ="estadoF"id="estadoF" value='<?php echo $profesor->estadoPro; ?>'>
             
                <option>Activo</option>
                <option>Inactivo</option>
                
                
            </select>

        </div>

    </div>

   

</div>
<!-- /.row -->

<div class="row">

    <div class="col-lg-1">
        <button class="btn btn-success waves-effect waves-light" type="submit" name="Actualizar">Actualizar
            <!--?php echo Form::submit("Ingresar","class: boton"); ?-->
        </button>
    </div>
    <div class="col-lg-1">
        <div class="actions">
            <?= Html::linkAction("", 'Volver', 'class="btn btn-danger"') ?>
        </div>
    </div>

</div>
<!-- /.row -->

<?php echo Form::close(); ?>